### ISSUE TITLE
[Bug] Crash upon startup

### ISSUE THREAD

**Issue by danielphan2003** [toasterofbread/spmp#105]
**Describe the bug**
The app crashes every time I reboot my phone upon unlocking.

**To Reproduce**
Steps to reproduce the behaviour:
1. Reboot the phone
2. The app crashes after unlocking

**Expected behaviour**
TBD

**Environment**
- Pixys OS Android 13
- 0.1.3
- Signed into Youtube

**Screenshots**
None.

**Logs**
https://bin.kv2.dev/~64cf273ce599576ea02d8489

**Comment by toasterofbread** [comment]
So it crashes on boot, without you even opening the app? How does the error appear?
