### ISSUE TITLE
[Bug] Longer playlists not loading

### ISSUE THREAD

**Issue by ElizabethWega** [toasterofbread/spmp#112]
**Describe the bug**
I have tried playing two of my playlists, one contains 3356 songs and the other 104 of them. The app refuses to progressively load playlists as I scroll further down. It stops loading at one fixed point and does not load further, not even when refreshed.

**To Reproduce**
Steps to reproduce the behaviour:
1. While logged in to YouTube, inside SpMp
2. Go to the playlist with 3356 songs: https://music.youtube.com/playlist?list=PLYAIm_Hd-7uEPu7-Moq6kAd8EBc1S-qd-&feature=share
3. Go to the playlist with 104 songs: https://music.youtube.com/playlist?list=PLYAIm_Hd-7uHr5jju7_f5zt0nppPFTQ-m&feature=share
4. Scroll down to load other/all songs. First playlist (3356 songs) stops loading once it reaches this song: https://music.youtube.com/watch?v=GoajksPvr1k&feature=share   Second playlist stops loading once it reaches this song: https://music.youtube.com/watch?v=RFA7rLU14Xo&feature=share
5. Error is displayed 

**Expected behaviour**
As with any other online music player, such as Spotify, YT Music, ViMusic, I expect the app to load more songs on the playlist as I scroll further down (cover image, song name, artist, duration)

**Environment**
- Android 13
- SpMp version: 0.1.3
- Accounts: Logged into a YT Music account (via "Log in manually" option)

**Comment by toasterofbread** [comment]
Thanks, this is a case I never tested. Will work on a fix.
