### ISSUE TITLE
backup (enhancement)

### ISSUE THREAD

**Issue by Wjxfi** [toasterofbread/spmp#118]
listening history, playlists, song list, library, download history.

I think this is the most important feature in the app since my phone might break, and I'm trying to give up on google since it's bad....

please ...

**Comment by toasterofbread** [comment]
What do you mean by backup? Do you want your data saved to a file, converted to the app's local data, or something else?

**Comment by toasterofbread** [comment]
Sorry, but that's pretty far out of this project's scope. You might want to take a look at other tools or libraries like [ytmusicapi](https://github.com/sigma67/ytmusicapi).

**Comment by quazar-omega** [comment]
As I understood from @Wjxfi, the data they want saved is not the actual music files downloaded from youtube, but rather the app's own data related to the playback history as well as any lists created from within it
