### ISSUE TITLE
[Bug] search bar not visible

### ISSUE THREAD

**Issue by zerobun** [toasterofbread/spmp#123]
**Describe the bug**

When you are searching for a song using thr search system, and you are typing on the search bar, the search is bar doesn't come up and jus stays at thr bottom and so you can't see what you are typing

**Steps To Reproduce**

1. Use the search system
2. Click on th search bar 
3. Start searching 
4. Won't be able to see thr search bar and thr content you are typing

**Expected behaviour**

Sine thr search bar is located at the bottom like this:
![Screenshot_2023_0821_042116](https://github.com/toasterofbread/spmp/assets/127630316/acbac75e-8cfd-402b-a30d-5e9327a8e7ab)
When clicked I expected it to go up at the top of thr screen while I'm using thr keyboard and typing our whatever I'm searching for. But it doesn't do that and just stays there. 

**Environment**
- OS name and version (e.g. Android 13): vivo y11 android 11
- SpMp version (include commit hash if you are using a non-release build): 0.1.4
- Accounts (were you signed in to YouTube, Discord, etc. in the app?): onky YouTube music

**Screenshots**

![Screenshot_2023_0821_042258](https://github.com/toasterofbread/spmp/assets/127630316/698ceaad-9a7d-4170-a58f-ed4da70363f9)

**Logs**

**Comment by toasterofbread** [comment]
Are you using a custom keyboard? In the GIF you sent it looks like the search bar is being moved too far up the screen, rather than being covered by the keyboard.

**Comment by toasterofbread** [comment]
This *might* have been fixed by [f1354f8](https://github.com/toasterofbread/spmp/commit/f1354f8f910997c3bc05ff6d39d018fc8b1aa4f9), but I doubt it. Please report here with the result if you're able to test it.

**Comment by zerobun** [comment]
> Are you using a custom keyboard? In the GIF you sent it looks like the search bar is being moved too far up the screen, rather than being covered by the keyboard.

Yes, I'm using Microsoft SwiftKey and yea I jus realized it goes fully up

**Comment by zerobun** [comment]
> This _might_ have been fixed by [f1354f8](https://github.com/toasterofbread/spmp/commit/f1354f8f910997c3bc05ff6d39d018fc8b1aa4f9), but I doubt it. Please report here with the result if you're able to test it.

Unfortunately I can't test it, so I'll just wait for a new release and hope it's fixed but yes thanks for trying to fix it.

**Comment by toasterofbread** [comment]
I'll assume this was fixed for now. If you find it wasn't fixed when you're able to test it, comment here again and I'll reopen this.
