### ISSUE TITLE
[Feature] Embed song lyrics into downloaded song for offline viewing. 

### ISSUE THREAD

**Issue by zerobun** [toasterofbread/spmp#125]
When a song is downloaded for offline play, the lyrics should be embedded into the song so when you play the song offline, you can see the lyrics.

**Comment by Berserk0001** [comment]
Can you please develop this feature soon?

**Comment by Berserk0001** [comment]
@toasterofbread can you release this feature in the next update? I think this feature is totaly needed....

**Comment by Berserk0001** [comment]
Many thanks..
