### ISSUE TITLE
Is there any way to reduce the size of the player?

### ISSUE THREAD

**Issue by dainvincible1** [toasterofbread/spmp#129]
![image](https://github.com/toasterofbread/spmp/assets/127825700/9f1a5722-7c13-4b5f-9cd7-db68a73a52b0)

**Comment by dainvincible1** [comment]
> What version of Android are you using?

@toasterofbread android 10

**Comment by toasterofbread** [comment]
Strange, I'm not able to reproduce this. What type of system navigation (like gesture navigation or 3-button) are you using, and are using any mods (like Magisk modules) that change the appearance of the navigation bar? I don't see the navigation bar in the screenshot, is that what it actually looks like on your screen or is it just hidden in the screenshot?

**Comment by toasterofbread** [comment]
[0c4b35d](https://github.com/toasterofbread/spmp/commit/0c4b35d41ad739e7e9d5d6afeb35eeda0bdcda1f) should have fixed or at least improved this issue. It would be great if you could [test](https://github.com/toasterofbread/spmp/actions/runs/5979523063) it and report any differences.

**Comment by dainvincible1** [comment]
> [0c4b35d](https://github.com/toasterofbread/spmp/commit/0c4b35d41ad739e7e9d5d6afeb35eeda0bdcda1f) should have fixed or at least improved this issue. It would be great if you could [test](https://github.com/toasterofbread/spmp/actions/runs/5979523063) it and report any differences.

@toasterofbread sorry for late reply but the issue is still there. maybe its something due to the phone, when i tried the app in a tablet then this issue was not there
![Screenshot_2023-09-20-22-48-31-71_7494cfb0f4df78e8ea8a89ba4b755132](https://github.com/toasterofbread/spmp/assets/127825700/74dc2d2b-c054-4e80-8b41-15150def723f)

**Comment by toasterofbread** [comment]
Are you using the commit I mentioned? If not, try with the latest build from the repo actions (I don't think anything's changed but you never know).

If that doesn't work then go to the in-app settings, developer, UI debug info, screenshot that page and upload it here please.

**Comment by dainvincible1** [comment]
![Screenshot_2023-09-22-10-14-45-67_7494cfb0f4df78e8ea8a89ba4b755132](https://github.com/toasterofbread/spmp/assets/127825700/4bec71b8-1eab-47e6-95df-3cef6ba3929d)
  @toasterofbread here it is

**Comment by toasterofbread** [comment]
Looks like your OS is providing the wrong height for the navigation bar which from what I can tell is hidden, am I right?
I'll add an option to adjust/remove the navigation bar height for cases like these.

**Comment by dainvincible1** [comment]
> Looks like your OS is providing the wrong height for the navigation bar which from what I can tell is hidden, am I right? I'll add an option to adjust/remove the navigation bar height for cases like these.

yes, its hidden. thank you so much that'll be awesome.

**Comment by toasterofbread** [comment]
I've added a slider that can be used to adjust the system-reported navigation bar height, set it to zero and it should hopefully look fine. It's at the top of the 'Other' section.

**Comment by dainvincible1** [comment]
> I've added a slider that can be used to adjust the system-reported navigation bar height, set it to zero and it should hopefully look fine. It's at the top of the 'Other' section.

yes, it has been fixed, thank you very much 
![Screenshot_2023-09-23-20-18-57-36_e82a23cb50dd4a2f2e01332c4ab3b632](https://github.com/toasterofbread/spmp/assets/127825700/ad8409d2-9283-45fa-9d1a-5474367c697d)
