### ISSUE TITLE
[Bug] Doesn't show full liked playlist

### ISSUE THREAD

**Issue by EDFO1** [toasterofbread/spmp#130]
My liked playlist has around 397 songs in it, but the app only says 100 and doesnt show all of them

**Steps To Reproduce**

1. Open app
2. Press on the liked songs 

**Expected behaviour**
Show all my liked songs

**Environment**
- Android 13
- SpMp version 0.1.4
- Signed in to YouTube

**Comment by toasterofbread** [comment]
Duplicate of #112 

Just as a heads up if you decide to test a build, playlist loading is currently broken in the most recent couple of commits
