### ISSUE TITLE
[Bug] Latest builds failing to launch

### ISSUE THREAD

**Issue by owencz1998** [toasterofbread/spmp#134]
So i haven't been able to access the debug app for a while about 3 debug versions back it doesn't load at all maybe this is due to a rewrite or a bug just a heads up if your not aware 😄

![Screenshot_20230901_070314.jpg](https://github.com/toasterofbread/spmp/assets/96526481/0d50644d-0b8b-4e91-af96-3b6d077a469c)

**Comment by toasterofbread** [comment]
Did you try clearing the app's data?

**Comment by toasterofbread** [comment]
If clearing data doesn't work, please provide the logs using an app like [this](https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en&gl=US&pli=1)

**Comment by owencz1998** [comment]
Ahh that's strange I did that before and didn't work but now is 🤣🤣
