### ISSUE TITLE
Preventing music video playback of album songs

### ISSUE THREAD

**Issue by rickdtc** [toasterofbread/spmp#136]
This, gwawun and blackhole, play music video versions of audio in an album but vimusic and innertune don't, what is reason for this and is it possible to have spmp play the audio versions of songs in an an album?

**Comment by toasterofbread** [comment]
Can you provide the URL of an album that does this?

**Comment by rickdtc** [comment]
https://music.youtube.com/playlist?list=MPREb_VyzmiRrWrDA

Sure thing, this one

**Comment by toasterofbread** [comment]
Fixed!

**Comment by rickdtc** [comment]
Thanks
