### ISSUE TITLE
Mini player flash bug

### ISSUE THREAD

**Issue by Savvkey** [toasterofbread/spmp#142]
### Tip

- when I put [] it means that I'm mentioning an option from the apps settings or a function like in the case of the minimized now playing menu (i mean the bar at the bottom of the app with currently playing song)
- (it's a little bit hard to read second point just try to ignore parentheses quotes to understand it better)

### Issue description

- When starting a new queue, regardless of cover cash or anything, every time on any conditions (even when songs are fully downloaded) the [minimized now playing menu] flashes the default theme color just before switching to the [now playing mode] selected by the user.
- this is quite strange also because when you start a new queue  (by disabling [persistent queue] and just closing app from recents and re-opening) from a song that was already "loaded" (by playing it in the current session) this bug doesn't happen, while by just killing the app (from the "kill app" android option or "force stop") this loading by session gets reset, and starting a queue from the song that you played before killing the app will need to load again and as such the bug will happen again. I want to point again at the fact that this bug is not related to app cash (or at least the cash shown on android settings) from what i was able to test. 

### Video demonstration

- https://github.com/toasterofbread/spmp/assets/103321812/3bae2981-85e2-4a71-a6bb-eacd40bfbdd9

### Opinions for the fix

- just a bug that needs to be fix
- and something strange about another type of hidden cash (maybe or idk) that fixes this bug after it happened once, persists trough removing from recents but resets after app is force closed.

### Testing environment

- OS: android 13
- Buid: e10058e
- Signed to youtube, not signed to discord

**Comment by toasterofbread** [comment]
Same bug as #141
