### ISSUE TITLE
Accent colour not updating in some cases

### ISSUE THREAD

**Issue by Savvkey** [toasterofbread/spmp#143]
### Tip

- when I put [] it means that I'm mentioning an option from the apps settings or a function like in the case of the minimized now playing menu (i mean the bar at the bottom of the app with currently playing song)ù

### Issue description
- When going to a previous songs on the queue the [now playing theme modes] just doesn't work for every single song that's before the current one, and is replaced with the accent color from the [current theme]. 
- Every time you go forward on the queue the previous song gets bugged out like all the others, and the loop repeats.

### Video demonstration

- https://github.com/toasterofbread/spmp/assets/103321812/65fb37eb-4d08-4211-b7fa-f15d7ba745b0
- https://photos.app.goo.gl/CTfnW9vfNtVbgjbm9 (seems like github video doesn't work)

### Testing environment

- OS: android 13
- Buid: e10058e
- Signed to youtube, not signed to discord

**Comment by toasterofbread** [comment]
Interesting, I can't believe I never noticed this. Will fix soon.
