### ISSUE TITLE
Disable show filters error icon

### ISSUE THREAD

**Issue by Savvkey** [toasterofbread/spmp#148]
**ISSUE DESCRIPTION**

- when [show filters if available] setting of the home page is off it shows a rather confusing icon
- I understand that finding a place to put search option could be a problem, but if someone prefers to not have filters they for sure wouldn't like even an error icon like that

**SCREEEN**

- https://github.com/toasterofbread/spmp/assets/103321812/98e4875c-79aa-434d-8de0-f3f6a5f926f5

**TESTING ENVIRONMENT**

- OS: android 13
- Build: 09e441b
-  Logged to YouTube

**Comment by toasterofbread** [comment]
Fixed by https://github.com/toasterofbread/spmp/commit/2b236eef6cfbb4d834698d1eaa84ccf84df954f4
