### ISSUE TITLE
Is there any way to remove songs from downloads?

### ISSUE THREAD

**Issue by dainvincible1** [toasterofbread/spmp#149]

**Comment by toasterofbread** [comment]
If you have a question, please ask in discussions or in the Discord server. You could also just create a feature suggestion.

As for the actual question, could you be more specific? Songs that are in-progress downloading should be cancellable through the notification. Downloaded songs aren't removable from within the app at the moment, but you can always just delete them from the library folder directly.

**Comment by dainvincible1** [comment]
> If you have a question, please ask in discussions or in the Discord server. You could also just create a feature suggestion.
> 
> As for the actual question, could you be more specific? Songs that are in-progress downloading should be cancellable through the notification. Downloaded songs aren't removable from within the app at the moment, but you can always just delete them from the library folder directly.

sorry, i didnt know there was a discord server, thanks
