### ISSUE TITLE
[Bug] Specific songs fail to play

### ISSUE THREAD

**Issue by dainvincible1** [toasterofbread/spmp#150]
I tried to play "Viva La Vida" by cold play but it wasnt playing but other songs were playing 

https://github.com/toasterofbread/spmp/assets/127825700/994d43b2-7f87-4128-bf1c-804240798fc3

**Comment by dainvincible1** [comment]
> As said in the issue template, please provide the app version and/or the hash of the commit you are using, as well as whether you're signed in to YouTube or not.
> 
> If you are signed in, see if signing out fixes it. If not, please also try clearing the app's data.

thanks its fixed.

**Comment by toasterofbread** [comment]
> thanks its fixed

👍 What fixed it, was it signing out or clearing the app's data? Were you signed in in the first place?

**Comment by dainvincible1** [comment]
> > thanks its fixed
> 
> 👍 What fixed it, was it signing out or clearing the app's data? Were you signed in in the first place?

yes..i was signed in. i cleared the cache first then played the song, the song got played. then i signed in again to see if the song still plays and the song played, thanks
