### ISSUE TITLE
proprietary components added

### ISSUE THREAD

**Issue by IzzySoft** [toasterofbread/spmp#155]
The latest release added proprietary components: Firebase and FireStore, so the app is no longer fully FOSS. Not sure for what those dependencies are needed – maybe you could replace them by something FOSS, like [appwrite](https://github.com/appwrite/appwrite) or [Supabase](https://supabase.com/)?

**Comment by toasterofbread** [comment]
Yeah, I realised this as well. Working on replacing Firebase with Supabase literally right now.

**Comment by IzzySoft** [comment]
Wonderful, thanks! Looking forward to the next release then to drop the additional anti-feature again :smiley:

**Comment by IzzySoft** [comment]
Hey, cool! I just dropped **ALL** of the AntiFeatures (effective with the next sync in about 24h): No more Firebase, no more Firestore \o/ Thanks for the great work!

**Comment by toasterofbread** [comment]
> Hey, cool! I just dropped **ALL** of the AntiFeatures (effective with the next sync in about 24h): No more Firebase, no more Firestore \o/ Thanks for the great work!

Great, thanks!
