### ISSUE TITLE
[Bug] YouTube premium content appears but isn't playable

### ISSUE THREAD

**Issue by talkingkittycat** [toasterofbread/spmp#160]
**Describe the bug**

Songs from certain artists will never play, it will simply buffer forever.

**Steps To Reproduce**

1. While logged in to YouTube
2. Go to 'Akatsuki Records'
3. Click on any song
4. Song will never play

**Expected behaviour**

Song plays normally.

**Environment**
- OS name and version (e.g. Android 13): LineageOS 20 (Android 13 based)
- SpMp version (include commit hash if you are using a non-release build): Commit 4802bf8, but still appears on latest F-Droid release
- Accounts (were you signed in to YouTube, Discord, etc. in the app?): Youtube only, with premium

**Screenshots**

https://litter.catbox.moe/kqqmqz.mp4

**Logs**
https://paste.ee/p/tfdyx 
Stacktrace I received from clicking on unplayable songs in am album too quickly, I assume this is related.

**Comment by toasterofbread** [comment]
I'm not able to reproduce this, but just to be sure I'm not testing with the wrong songs, could you send the URL of some songs that don't work for you?

- Did you change the streaming backend by any chance? (the first option in the download settings section)
- Do the songs work in other YouTube clients? If not, this might be a region blocking issue or something similar on YouTube's end.
- Are you using a VPN or anything like that?

SpMp should log information about playing songs, could you find the logs for when song playback failed and upload them please? You can use a tool like Logcat or try [capturing a bug report](https://developer.android.com/studio/debug/bug-report).

>  Stacktrace I received from clicking on unplayable songs in am album too quickly, I assume this is related.

I don't think that's related to this, but thanks for reporting (I'll try to get that fixed as well).

**Comment by talkingkittycat** [comment]
Thank you for the reply. Here's a couple of songs that are affected.
https://music.youtube.com/watch?v=mq-0NxdbrQ0
https://music.youtube.com/watch?v=lDzA_cnYuak
https://music.youtube.com/watch?v=ycsDwNAXTmw

- I'm using the default Youtubei backend. I also tried Newpiped but no song would play through it.
- I have tested on other Youtube clients, specifically InnerTube, ViMusic, and Newpipe. The song's wouldn't appear on the first two and Newpipe threw an error about being premium only. 
- I haven't been using a VPN for this. 

Here's a app log pulled from Logcat. The playback issues should be near the bottom.
https://litter.catbox.moe/hlw8aj.txt

**Comment by toasterofbread** [comment]
Seems like the issue is not being able to play premium-only content then. I won't be able to support playing premium content, as it's probably DRM protected (and I don't have YouTube premium to be able to test anyway).

I've had a look at InnerTune (which I assume is what you meant by InnerTube) as it also supports logins, but I didn't see any code related to hiding premium content. Were you logged in to InnerTube when you tried it?

**Comment by toasterofbread** [comment]
Forgot to mention this here, but premium content is now playable if you're logged in with a premium account (added in eaef6ed).
