### ISSUE TITLE
[Bug] Preferences & Log in manually bug

### ISSUE THREAD

**Issue by ElizabethWega** [toasterofbread/spmp#164]
**Describe the bug**
Upon re-installing the app, I wanted to log into my YouTube Music acoount. I went to 'Preferences', clicked 'sign in' and chose the 'log in manually' option. It used to work in 0.2.0 (since 0.2.1 it does not). I try typing in the headers, but no letters get inputed. I try pasting the headers, but no information shows in the 'headers' box. Once presssed, the input box moves up on the screen (see screenshot 1). Pressing the 'X' (cancel) does nothing, but pressing '✓' (tick/confirm) returns an error message (see screenshot 2). Additionally, going back to main 'Preferences' page (at least trying to) sends me to the Home Page of the SpMp. I go back and forth; pressing the 'cog' ⚙️ icon shows me the 'log in manually' page, where I have to enter my Headers information. Pressing the 'back' button returns me to the Home Page or Starting Page of SpMp. It refuses to show me all the preferences (available) page until I force close the app and open it again. Giving it one more try results in the very same error. The same thing goes for 0.2.1 version of the app (thought someone's going to bring it up, but as far as I can see, no one has).
**Steps To Reproduce**

1. While not logged in to YouTube
2. Go to 'Preferences'
3. Click on 'Sign in'
4. Click on 'Log in manually' option
5. Try to input/paste the Headers info
6. Try clicking 'cancel' and/or 'confirm'
7. Try going back to the Home Page of the 'Preferences' tab
8. Error is displayed 

**Expected behaviour**
To be able to insert the headers info into the headers box, either via keyboard or 'paste' option. To be able to return to the 'Preferences' Main Page from the 'log in manually' page using the 'return' (go back) button.

**Environment**
- OS name and version: Android 13
- SpMp version (include commit hash if you are using a non-release build): 0.2.2
- Accounts (were you signed in to YouTube, Discord, etc. in the app?): none
- 
**Screenshots**
![screenshot 1](https://github.com/toasterofbread/spmp/assets/88385659/66696847-19cf-4516-a69a-26f9b954b37f)
![screenshot 2](https://github.com/toasterofbread/spmp/assets/88385659/7c20abc8-34a4-4664-9a5a-2335b78b075c)

**Comment by toasterofbread** [comment]
Should be fixed!
