### ISSUE TITLE
Specify song download directory

### ISSUE THREAD

**Issue by Berserk0001** [toasterofbread/spmp#171]
Please add an option to download songs in any particular directory...

**Comment by toasterofbread** [comment]
Songs are downloaded into the library folder which can be changed in the library settings. Is this not what you're looking for?

**Comment by Berserk0001** [comment]
Oh..sorry, my mistake i did'nt see it...

**Comment by Berserk0001** [comment]
Oh..sorry, my mistake i did'nt see it...

**Comment by Berserk0001** [comment]
Oh..sorry, my mistake i did'nt see it...
