### ISSUE TITLE
DataParseException when logging into YT Music

### ISSUE THREAD

**Issue by Eiim** [toasterofbread/spmp#176]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Attempt to log into YT Music with manual credentials
2. Doesn't show logged in view.
3. Go to Preferences, clock the "no internet" symbol
4. DataParseException shown

### Expected behavior

Honestly, I'm not sure as I haven't gotten the app working yet, but I assume it would log in and show you account-specific information.

### Actual behavior

DataParseException thrown, no personalized/account-specific info available

### Screenshots / recordings

Screenshots are in the non-debug version of the app but I replicated it with the latest debug version.
![Screenshot_20231021_143020](https://github.com/toasterofbread/spmp/assets/24627058/4e9c9f18-ee10-4e06-9bde-5f255ba242f4)
![Screenshot_20231021_143032](https://github.com/toasterofbread/spmp/assets/24627058/0defa9a4-2212-493e-a974-089e94f2ee42)

### Logs

I would upload to paste.ee but that didn't work, in a potentially related JsonIOException:
![Screenshot_20231021_143226](https://github.com/toasterofbread/spmp/assets/24627058/fcdfcb00-b1d6-4b8b-b7ea-ded288961a3f)
I was able to copy a log, though: [spmplog.txt](https://github.com/toasterofbread/spmp/files/13061530/spmplog.txt)

### SpMp version

0.2.3, 4fc924a debug

### Android version

Android 13

**Comment by ie-rosie** [comment]
I also have this bug, but I am able to upload to Paste.ee and it displays the following message: _Can't toast on a thread that has not Looper.prepare()_. 
Additionally I can't log in not even with the default option as it shows a NetworkOnMainThreadException error.

**Comment by toasterofbread** [comment]
@ie-rosie Did you try the latest build? The NetworkOnMainThreadException should have been fixed in bf635b7.

**Comment by toasterofbread** [comment]
> I would upload to paste.ee but that didn't work, in a potentially related JsonIOException:

@Eiim Could you upload the logs for the IOException please?

**Comment by Eiim** [comment]
Sure, it's jsut one line: `com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

**Comment by Eiim** [comment]
Actually, it's JsonSyntaxException (above) in the debug build and a JsonIOException in the regular build. I hadn't noticed that before. The regular build's error line is `com.google.gson.JsonIOException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

**Comment by toasterofbread** [comment]
@Eiim Try with d75d4af, it should display the full error when paste.ee uploading fails. Uploading to paste.ee is different from just copy-pasting the error because it includes the JSON data involved with the error (the data displayed when you press "Show JSON data").

**Comment by Eiim** [comment]
Got a full stacktrace now: ![past.ee error stacktrace.txt](https://github.com/toasterofbread/spmp/files/13064634/past.ee.error.stacktrace.txt)

**Comment by ie-rosie** [comment]
@toasterofbread, I have the latest build from Github running on Android 10. This is what I got from trying to log in normally https://paste.ee/p/cBZ1f. I will later send the error log when using the manual method.

**Comment by toasterofbread** [comment]
> @toasterofbread, I have the latest build from Github running on Android 10. This is what I got from trying to log in normally [paste.ee/p/cBZ1f](https://paste.ee/p/cBZ1f). I will later send the error log when using the manual method.

Which specific commit are you using? Please try uploading the same stack trace using a debug build.

**Comment by toasterofbread** [comment]
@Eiim Please try with 9aeec8f3dfffcb85f336e40d584f65c72bbcd2ec

**Comment by Eiim** [comment]
With b66d9c0: https://paste.ee/p/zDcaw

When I click on "Show JSON", it's corrupted. For some reason GitHub won't let me upload the screenshot from my phone, I'll try when I'm at my computer later.

**Comment by Fern-Leaves** [comment]
I am experiencing this same issue https://paste.ee/p/xuQ0w

**Comment by Satanarious** [comment]
Same issue while loggin in, this  [error](https://paste.ee/p/efWUM) is shown.

**Comment by toasterofbread** [comment]
> I am experiencing this same issue [paste.ee/p/xuQ0w](https://paste.ee/p/xuQ0w) it happens when I press the settings button whilst logged into youtube music and when I press the search button

Not the same issue, moved to #181

**Comment by toasterofbread** [comment]
> Same issue while logging in, this [error](https://paste.ee/p/efWUM) is shown. Also could you explain the manual method, I couldn't seem to find any post request on YouTube Music with Developer mode, just fetch or XHR.

Fixed by bf635b7dcb91ea3b778318de5c52eceed7ead8cb. Not sure why you're not seeing post requests, I'm not sure how to help you with that.

**Comment by Eiim** [comment]
New data: https://paste.ee/p/jOyUn

**Comment by toasterofbread** [comment]
@Eiim 576989fc9e7d106c2437264a7c47e2f5ebdca3ef should hopefully fix this

**Comment by Eiim** [comment]
It seems to be fixed now, awesome! Though now I have another issue to open 😊
