### ISSUE TITLE
Cannot pin any local playlists

### ISSUE THREAD

**Issue by DestinyofYeet** [toasterofbread/spmp#177]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open the app
2. Click on the music icon in the top right
3. Open any local playlist
4. Try to pin the playlist

### Expected behavior

The playlist should appear at the top of the home screen, as online playlists already do.

### Actual behavior

An error get's thrown.

### Logs

https://paste.ee/p/6RtsB

### SpMp version

0.2.3, [debug 4fc924a](https://github.com/toasterofbread/spmp/commit/4fc924a46a8d6857e14ebe09411ba79f9176d1e2)

### Android version

Android 12 - Lineage OS (vayu with MicroG)

**Comment by toasterofbread** [comment]
Thanks for the report!
