### ISSUE TITLE
Cannot remove song from an account playlist

### ISSUE THREAD

**Issue by DestinyofYeet** [toasterofbread/spmp#179]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Log into Youtube
2. Click on the Music Icon in the top right
3. Click on a playlist in your account
4. Try to remove a song from that playlist

### Expected behavior

The song should be removed from the playlist.

### Actual behavior

An exception is thrown and the song is not removed.

### Logs

https://paste.ee/p/yVKo8

### SpMp version

0.2.3, [debug b66d9c0](https://github.com/toasterofbread/spmp/commit/b66d9c092dfdf01dcd1d37679d6c3b0982c5e2e2)

### Android version

Android 12 - Lineage OS

### Additional information

A song can be already be added, but as said above, not removed.

**Comment by Geigerkind** [comment]
@toasterofbread sorry to ask here, but how do you actually remove a song from an account playlist. Is there some gesture or button I cant find?

**Comment by toasterofbread** [comment]
@Geigerkind Just long-press / right-click a song to open the details menu, a button to remove should be there (or alternatively, use the multiselect bar). According to #359 this might be broken at the moment, I haven't tested this yet.

**Comment by Geigerkind** [comment]
@toasterofbread , hmm, I open my YT Account playlist and long press on a song. Then a context menu opens, but in it I have pretty much every option but to remove it from this playlist. Is that intended? Otherwise Im going to open a ticket for it :)
