### ISSUE TITLE
[Bug] (Seemingly) recursive loop when saving item data

### ISSUE THREAD

**Issue by toasterofbread** [toasterofbread/spmp#181]
https://paste.ee/p/xuQ0w

It happens when I press the settings button whilst logged into youtube music and when I press the search button.

_Originally posted by @Fern-Leaves in https://github.com/toasterofbread/spmp/issues/176#issuecomment-1780234157_

**Comment by tanmaytez** [comment]
Can u tell me how do I log in?

**Comment by toasterofbread** [comment]
Closing in favour of #184 as it contains a more complete stack trace

**Comment by Eiim** [comment]
Sorry, didn't realize these were the same.
