### ISSUE TITLE
[FEATURE] Using SPMP as a Download platform

### ISSUE THREAD

**Issue by rigobert9** [toasterofbread/spmp#183]
I mainly use other, offline music readers by forxe of habit, but I love this app for all the navigation option available. I'd like to use it to browse, find and then download music.
Would it be possible to add switches to download music through a music format (ogg, m4a, mp3) and with metadata attached (such as thumbnails, lyrics, album and performer info ...), along with the planned change of being able to transfer the songs to a folder with their song name ?
Thanks for the incredible app, and please keep up the good work.

**Comment by toasterofbread** [comment]
Part of this implemented by a350af0 and 5edf002.
