### ISSUE TITLE
crashes when tapping a song in the search bar

### ISSUE THREAD

**Issue by 32bitx64bit** [toasterofbread/spmp#188]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Search any song 
Tap on song
Get a soft crash bug report

### Expected behavior

Tap a song
Be loaded into the player area

### Actual behavior

Tap a song from the search section
Soft crashes

### Logs

https://paste.ee/p/yAOgl

### SpMp version

195225d

### Android version

Android 14

### Additional information

Sorry for the amount of bug reports I'm doing.
Just trying to help improve the app. :)

**Comment by toasterofbread** [comment]
The database format has changed, you'll clear the app's data in order to use new commits.
