### ISSUE TITLE
Horizontal mode is bugged with the 3 buttons turned on

### ISSUE THREAD

**Issue by SecularSteve** [toasterofbread/spmp#190]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Basically open the app, and turn your screen horizontally with 3-button navigation on in "Gestures > System Navigation".

### Expected behavior

That the left and right side of the app aren't obscured by the buttons.

### Actual behavior

I can't use or interact with whatever's behind the buttons when turned horizontally.

### Screenshots / recordings

![Screenshot_2023-10-31_19-12-45~2](https://github.com/toasterofbread/spmp/assets/33793273/4bdaac05-b8b0-44a8-839b-efca6de06413)

![Screenshot_2023-10-31_19-17-34~2](https://github.com/toasterofbread/spmp/assets/33793273/12e80d4f-b940-40d9-a5a2-bb902cfa77fe)

### Logs

n/a unless stated otherwise

### SpMp version

0.2.3

### Android version

Android 12

### Additional information

n/a as far as I'm concerned

**Comment by toasterofbread** [comment]
I had to add padding for the navbar manually to each page so I *might* have missed something, but this should be fixed now.
