### ISSUE TITLE
[Feature] Show if Songs are explicit

### ISSUE THREAD

**Issue by JoeneckSpoeneck** [toasterofbread/spmp#192]
As the title says, it would be great to see if a song is explicit.

**Comment by toasterofbread** [comment]
How would SpMp check if a song is explicit? Is this a part of YouTube?

**Comment by SecularSteve** [comment]
> How would SpMp check if a song is explicit? Is this a part of YouTube?

Yep, and the feature's already in ViMusic and InnerTune for a while now.

For reference, here's a screenshot:

![Screenshot_2023-11-16_22-27-06~2.png](https://github.com/toasterofbread/spmp/assets/33793273/3f994461-7f87-4e7d-80c6-075a5f30222a)

The tiny E in a square is usually next to the Artist to indicate this about the song.

Here's a rounded one in case you need it to make it stand out a bit:

https://www.svgrepo.com/svg/403771/letter-e

**Comment by toasterofbread** [comment]
Oh, so that's what that symbol is, I'd been wondering about that. I should be able to implement this.
