### ISSUE TITLE
Double F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [toasterofbread/spmp#193]
As your app reached F-Droid.org more than 2 weeks ago, at this time I'd usually remove it from my repo (which runs on personal space, so I try to not "exceed my quotas"). Checking, I found your Readme still links here. So to not confuse folks with a 404, I'd rather wait with the app removal on my end until the badge has been removed on yours. Shall we proceed?

**Comment by toasterofbread** [comment]
No problem, links have been removed from READMEs.

**Comment by IzzySoft** [comment]
Thanks! I've just triggered the removal here then, will be effective with the next sync in about 2.5 hours from now. Should the need arrive for a re-listing (or listing of a new app of yours), just let me know then.
