### ISSUE TITLE
HTTP error 400 upon signing in (account_menu, invalid argument)

### ISSUE THREAD

**Issue by AtlasC0R3** [toasterofbread/spmp#199]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open app
2. Sign in (whether by providing auth/cookie headers or using in-app browser)

### Expected behavior

I should be signed in to my Google/YouTube account inside the app, and can now freely use it.

### Actual behavior

Java RuntimeException, POST request to `https://music.youtube.com/youtubei/v1/account/account_menu` failed with an error 400.

### Screenshots / recordings

The screen recording demonstrates only the header input method. The text box input is invisible, as I have pasted the headers with one newline at the end, providing this side effect of not displaying the headers themselves (because I'd like not to dox myself).

https://github.com/toasterofbread/spmp/assets/39468657/9dcb02ee-0e41-4f4a-b676-3440ae1c139a

### Logs

Replaced auth and cookie headers with "loremipsum"

```
java.lang.RuntimeException: Request failed
Request=Request{method=POST, url=https://music.youtube.com/youtubei/v1/account/account_menu?prettyPrint=false, headers=[accept:*/*, content-type:application/json, x-youtube-client-name:67, x-youtube-client-version:1.20221019.01.00, x-goog-authuser:1, x-origin:https://music.youtube.com, origin:https://music.youtube.com, user-agent:Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0, authorization:loremipsum, cookie:loremipsum]}
Request body={"context":{"client":{"hl":"en-CA","platform":"DESKTOP","clientName":"WEB_REMIX","clientVersion":"1.20230306.01.00","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0","acceptHeader":"text/html,application/xhtml+xml,application/xml;q\u003d0.9,image/avif,image/webp,*/*;q\u003d0.8"},"user":{}}}
Response={
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}

	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.ApiKt.failure(SourceFile:98)
	at com.toasterofbread.spmp.youtubeapi.YoutubeApiKt.executeResult(Unknown Source:29)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YoutubeMusicApi.performRequest-0E7RQCE(Unknown Source:12)
	at com.toasterofbread.spmp.youtubeapi.YoutubeApi$DefaultImpls.performRequest-0E7RQCE$default(Unknown Source:12)
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YTMUserAuthStateEndpoint$byHeaders$3.invokeSuspend(SourceFile:151)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
```

### SpMp version

0.2.4, though it is noted that I have had these issues on prior versions as well as the current debug.

### Android version

Android 14 Beta, AP11.231020.013.A1

### Additional information

InnerTune and yt-dlp, other third-party projects that utilize YouTube Music account authorization, can access, play and download from my account without issue.
Obviously, the authorization keys are redacted only in this issue; the actual app itself has access to them.

**Comment by AtlasC0R3** [comment]
Did some fiddling in a Python terminal; found the issue. At least, I'm pretty sure.

The problem lies inside the POST request's data: the `hl` keyword. YT Music's API expects `hl` to be the language (in my case, en) and another key, `gl` to be the country (in my case, CA).
What it instead gets with SpMp, prompting the status code 400, is both of them crammed into `hl`.
![py_QSYjjhlHZR](https://github.com/toasterofbread/spmp/assets/39468657/64988314-9779-48dc-8b4e-bcd3bde44eb8)

**Comment by toasterofbread** [comment]
Should be fixed, thanks for the report!

**Comment by AtlasC0R3** [comment]
Can confirm, signs in and interacts with my account without issue now.
