### ISSUE TITLE
[Bug] Some songs not loading

### ISSUE THREAD

**Issue by vjaykrsna** [toasterofbread/spmp#200]
Songs often get stuck on loading
From my guess this happens when i have already played a song once and if the song was partially played and downloaded when played for second time it plays the downloaded part and then gets stuck

**Comment by toasterofbread** [comment]
Please provide some example IDs of songs that get stuck. Are you certain that the songs getting stuck were playing before?

**Comment by toasterofbread** [comment]
Also, *please use the issue form for bug reports*.

**Comment by vjaykrsna** [comment]
Can't make a big report because this doesn't happens always but i faced it 3 times from yesterday.
When i faced this issue i deleted local file and played song again and it worked fine

**Comment by ezzyshabbir05** [comment]
It's an issue related to Piped API. Using Youtubei works fine while using stream method Piped API gets stucked and doesn't load the song atleast for me.

https://github.com/toasterofbread/spmp/assets/76464869/fbc8ef73-d6e6-47ae-8c02-e4442260941c

**Comment by toasterofbread** [comment]
This might be due to region blocking or something similar on Piped's end. Is there anything in the logs to do with song loading?
