### ISSUE TITLE
[Feature] Ability to export user settings.

### ISSUE THREAD

**Issue by zerobun** [toasterofbread/spmp#201]
The ability to **export** and **import** users settings.

Maybe also the option to choose which part of the settings are to be exported in a **custom directory.**

For example in this picture it shows all the settings options.
![Screenshot_2023_1118_104820](https://github.com/toasterofbread/spmp/assets/127630316/edea7d68-c71f-444e-a6e6-7035cbc2fb3a)

When you choose to export your settings, you get the ability to click on **check boxes** to choose which settings options are getting exported  (general, filters and so on)

And maybe in the future, the option to **auto export/backup** settings with **library content** (songs and playlists) to a pre chosen custom directory.

**Comment by vjaykrsna** [comment]
Ability to choose is always good.
While exporting it is okay to export all settings but while importing/restoring it would be great if we had option to choose which part of settings to restore. That makes sense if you mess something up and want to import something others have.

Settings in this apps are pretty simple and straightforward btw.
