### ISSUE TITLE
[ENHANCEMENT] Better Player.

### ISSUE THREAD

**Issue by zerobun** [toasterofbread/spmp#202]
Better Player with more buttons added.

Something like this would be nice.
https://github.com/Sangwan5688/BlackHole/blob/main/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png?raw=true

**Comment by toasterofbread** [comment]
This is being discussed (and partially implemented) in [UI Design suggestions](https://github.com/toasterofbread/spmp/discussions/189).

**Comment by zerobun** [comment]
> This is being discussed (and partially implemented) in [UI Design suggestions](https://github.com/toasterofbread/spmp/discussions/189).

Ah OK thanks
