### ISSUE TITLE
Latest debug version does not function correctly.

### ISSUE THREAD

**Issue by DestinyofYeet** [toasterofbread/spmp#205]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open the debug app

### Expected behavior

The app should open and behave like normal. I should be able to use the app, see my youtube-feed and play music

### Actual behavior

The app opens, it shows my feed for a second, then it says "Youtube feed parsing failed" and I'm shown my local playlists. After a few seconds, the app goes dark and and clicking anything makes the app crash.

### Screenshots / recordings

https://nc.uwuwhatsthis.de/s/7QiJQYAr9T7qP64
or 
https://drive.google.com/file/d/1qDYS-s2prJo2kgVhitqJ7fTEc8KpEADQ/view?usp=sharing

### Logs

Log captured with logcat [spmp_debug_log.txt](https://github.com/toasterofbread/spmp/files/13420127/spmp_debug_log.txt)

### SpMp version

Debug edf3bd3

### Android version

Android 12 - Lineage OS

**Comment by toasterofbread** [comment]
The database format has changed, so you'll need to clear your app's data. In general, if you're testing a debug build and it fails, please try clearing the data before reporting an issue.
