### ISSUE TITLE
[feature request] sync playlists and albums with account

### ISSUE THREAD

**Issue by gmankab** [toasterofbread/spmp#217]

**Comment by toasterofbread** [comment]
Please be more specific. You're already able to view/download account playlists as well as add, reorder, and remove items within them.

**Comment by gmankab** [comment]
can you please tell me how?

youtube music playlists section:
![Screenshot_20231222-210628](https://github.com/toasterofbread/spmp/assets/73340745/5e838e90-34cb-4356-9389-0db6829af356)

there is no liked music playlist in spmp:
![Screenshot_20231222-210555](https://github.com/toasterofbread/spmp/assets/73340745/a86e70bc-479f-4593-b470-ca1f151967b9)

when i press update button nothing changes

also i can't find section for liked albums

**Comment by MissingNoIOI** [comment]
I think they mean to also show liked songs and liked albums in the library view. That's a feature I would be interested in too, since I normally listen to albums instead of playlists. Would be even more awesome if you could use different sorting methods, like by artist etc

**Comment by gmankab** [comment]
yes

**Comment by gmankab** [comment]
waiting for a release to test it :)
