### ISSUE TITLE
Crash on opening any of my playlists 

### ISSUE THREAD

**Issue by Satanarious** [toasterofbread/spmp#219]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Click on any playlist of your own

### Expected behavior

Playlist should open

### Actual behavior

Crashing the app with sqlite error 

### Logs

Error: https://api.paste.ee/p/id0dp

### SpMp version

0.2.4

### Android version

Evolution X Android 14

### Additional information

I've Also tried it on Evolution X Android 13 before I updated.

**Comment by vichusachu** [comment]
Sir,is it possible to get spmp apk without any restrictions inorder to edit it on my personal choice🥲,just want a version without obfuscation

**Comment by toasterofbread** [comment]
Caused by #161. As a workaround, deleting app data should fix this issue.
