### ISSUE TITLE
It doesn't play the downloaded songs offline

### ISSUE THREAD

**Issue by Azzman1984** [toasterofbread/spmp#221]
I downloaded an album and then I turned the WiFi off to see if it plays the album offline and it doesn't at all

Here's the screenshot of the downloaded album
![Screenshot_20240120_004227](https://github.com/toasterofbread/spmp/assets/150800081/f632d650-8f9a-4fe9-b8df-bc81e3318590)

Then I press play when after I turned the WiFi off and it doesn't work at all

![Screenshot_20240120_004339](https://github.com/toasterofbread/spmp/assets/150800081/15f8123c-1679-4700-b079-db74346fb659)

If there's a way that u can fix this problem so I could play the downloaded album without WiFi then I would be very grateful.

**Comment by toasterofbread** [comment]
Please use the template when reporting a bug.

**Comment by Azzman1984** [comment]
> Please use the template when reporting a bug.
> 
> * What version/commit of SpMp are you using?
> * What version of Android are you using?
> 
> Please also provide the full content of the exception you show in your screenshot.

I done it on the issue post above this one
