### ISSUE TITLE
It doesn't play the downloaded song offline

### ISSUE THREAD

**Issue by Azzman1984** [toasterofbread/spmp#222]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. I downloaded the songs
2. I went on local playlists
3. Then clicked on local artists
4. Then clicked on play and it doesn't work

### Expected behavior

It should play the downloaded songs offline without the use of WiFi 

### Actual behavior

Then a message popped up saying a error occurred 
![298241270-15f8123c-1679-4700-b079-db74346fb659](https://github.com/toasterofbread/spmp/assets/150800081/ffb80230-8bf8-48c8-8642-bb0e3c0a52c7)

### Screenshots / recordings

![Screenshot_20240120_004249](https://github.com/toasterofbread/spmp/assets/150800081/85709a30-59dd-4e77-8023-08f4bc84dcf8)

![298241270-15f8123c-1679-4700-b079-db74346fb659](https://github.com/toasterofbread/spmp/assets/150800081/fc7b198b-28f4-4c5a-bf6e-a1b233bcb2ec)

### Logs

---STACK TRACE---
kotlin.NotImplementedError: An operation is not implemented.
	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance.getInitialSongs-IoAF18A(SourceFile:405)
	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance.access$getInitialSongs-IoAF18A(Unknown Source:0)
	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance$loadContinuation$1$1.invokeSuspend(SourceFile:164)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@33be57c, Dispatchers.IO]

---LOGCAT (last 110 lines)---
01-20 01:07:51.060 28496 30578 I CCodecBufferChannel: [c2.android.opus.decoder#807] Created output block pool with allocatorID 16 => poolID 1234 - OK
01-20 01:07:51.061 28496 30578 D CCodecBufferChannel: [c2.android.opus.decoder#807] Configured output block pool ids 1234 => OK
01-20 01:07:51.061 28496 30578 I CCodec  : [c2.android.opus.decoder] state->set(RUNNING)
01-20 01:07:51.061 28496 30578 I CCodecBufferChannel: [c2.android.opus.decoder#807] 4 initial input buffers available
01-20 01:07:51.099 28496 30565 D AudioTrack: setVolume(1.000000, 1.000000) pid : 28496
01-20 01:07:51.153 28496 28496 D MediaRouter: onRestoreRoute() : route=RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
01-20 01:07:51.153 28496 28496 V MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: performTraversals params={(0,0)(fillxfill) sim={adjust=nothing} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fl=81810100
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   pfl=16020040
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   apr=LIGHT_STATUS_BARS
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   bhv=DEFAULT
01-20 01:07:51.177 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fitSides= naviIconColor=0}
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=nothing} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fl=81810100
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   pfl=16020040
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   apr=LIGHT_STATUS_BARS
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   bhv=DEFAULT
01-20 01:07:51.178 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fitSides= naviIconColor=0}
01-20 01:07:51.185 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: updateBlastSurfaceIfNeeded mBlastBufferQueue=0x7ce78c9bb0 isSameSurfaceControl=true
01-20 01:07:51.185 28496 28496 I BLASTBufferQueue: update, w= 1080 h= 2400 mName = ViewRootImpl@3c6c15c[MainActivity] mNativeObject= 0x7ce78c9bb0 sc.mNativeObject= 0x7c77937ee0 format= -1 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
01-20 01:07:51.185 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=7 res=0x0 s={true 0x7d778b6850} ch=false seqId=0
01-20 01:07:51.209 28496 30565 D AudioTrack: getTimestamp_l(2170): device stall time corrected using current time 105424370688748
01-20 01:07:51.219 28496 30565 D AudioTrack: getTimestamp_l(2170): stale timestamp time corrected, currentTimeNanos: 105206460447135 < limitNs: 105424181860979 < mStartNs: 105424261860979
01-20 01:07:51.219 28496 30565 W AudioTrack: getTimestamp_l(2170): retrograde timestamp time corrected, 105424181860979 < 105424370688748
01-20 01:07:51.261 28496 28506 I terofbread.spmp: Background concurrent copying GC freed 424576(15MB) AllocSpace objects, 71(33MB) LOS objects, 49% free, 22MB/45MB, paused 187us,49us total 138.755ms
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: performTraversals params={(0,0)(fillxfill) sim={adjust=nothing} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fl=81810100
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   pfl=16020040
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   bhv=DEFAULT
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fitSides= naviIconColor=0}
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=nothing} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fl=81810100
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   pfl=16020040
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   bhv=DEFAULT
01-20 01:07:55.600 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]:   fitSides= naviIconColor=0}
01-20 01:07:55.610 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: updateBlastSurfaceIfNeeded mBlastBufferQueue=0x7ce78c9bb0 isSameSurfaceControl=true
01-20 01:07:55.611 28496 28496 I BLASTBufferQueue: update, w= 1080 h= 2400 mName = ViewRootImpl@3c6c15c[MainActivity] mNativeObject= 0x7ce78c9bb0 sc.mNativeObject= 0x7c779452a0 format= -1 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
01-20 01:07:55.611 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=10 res=0x0 s={true 0x7d778b6850} ch=false seqId=0
01-20 01:07:56.210 28496 30582 D BufferPoolAccessor2.0: bufferpool2 0x7cd7959218 : 5(28800 size) total buffers - 4(23040 size) used buffers - 275/280 (recycle/alloc) - 5/552 (fetch/transfer)
01-20 01:07:57.783 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: ViewPostIme pointer 0
01-20 01:07:57.845 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: ViewPostIme pointer 1
01-20 01:07:59.035 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: ViewPostIme pointer 0
01-20 01:07:59.107 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: ViewPostIme pointer 1
01-20 01:07:59.111 28496 30578 I CCodec  : [c2.android.opus.decoder] state->set(FLUSHING)
01-20 01:07:59.121 28496 30578 I CCodec  : [c2.android.opus.decoder] state->set(FLUSHED)
01-20 01:07:59.121 28496 30565 D MediaCodec: keep callback message for reclaim
01-20 01:07:59.121 28496 30578 I CCodec  : [c2.android.opus.decoder] state->set(RESUMING)
01-20 01:07:59.121 28496 30578 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
01-20 01:07:59.121 28496 30578 W Codec2Client: query -- param skipped: index = 1342179345.
01-20 01:07:59.121 28496 30578 W Codec2Client: query -- param skipped: index = 2415921170.
01-20 01:07:59.122 28496 30578 I CCodec  : [c2.android.opus.decoder] state->set(RUNNING)
01-20 01:07:59.122 28496 30578 I CCodecBufferChannel: [c2.android.opus.decoder#807] 4 initial input buffers available
01-20 01:07:59.123 28496 29931 W System.err: kotlin.NotImplementedError: An operation is not implemented.
01-20 01:07:59.124 28496 29931 W System.err: 	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance.getInitialSongs-IoAF18A(SourceFile:405)
01-20 01:07:59.124 28496 29931 W System.err: 	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance.access$getInitialSongs-IoAF18A(Unknown Source:0)
01-20 01:07:59.124 28496 29931 W System.err: 	at com.toasterofbread.spmp.youtubeapi.radio.RadioInstance$loadContinuation$1$1.invokeSuspend(SourceFile:164)
01-20 01:07:59.124 28496 29931 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
01-20 01:07:59.124 28496 29931 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
01-20 01:07:59.124 28496 29931 W System.err: 	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
01-20 01:07:59.124 28496 29931 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
01-20 01:07:59.125 28496 29931 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
01-20 01:07:59.125 28496 29931 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@33be57c, Dispatchers.IO]
01-20 01:07:59.215 28496 29930 I System.out: Retrieving logcat output...
01-20 01:07:59.215 28496 28496 I DecorView: [INFO] isPopOver=false config=true
01-20 01:07:59.215 28496 28496 I DecorView: updateCaptionType: isFloating=false isApplication=true hasWindowDecorCaption=false this=DecorView@dfcb6eb[]
01-20 01:07:59.215 28496 28496 D DecorView: setCaptionType = 0, this = DecorView@dfcb6eb[]
01-20 01:07:59.216 28496 28496 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=450 msg=resources_loaded
01-20 01:07:59.216 28496 28496 I DecorView: setWindowBackground: isPopOver=false color=ff171717 d=android.graphics.drawable.GradientDrawable@d427ae1
01-20 01:07:59.217 28496 28496 I MSHandlerLifeCycle: check: return. pkg=com.toasterofbread.spmp parent=null callers=com.android.internal.policy.DecorView.setVisibility:4412 android.app.ActivityThread.handleResumeActivity:5476 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
01-20 01:07:59.218 28496 28496 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@dfcb6eb[]
01-20 01:07:59.232 28496 28522 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
01-20 01:07:59.239 28496 28496 D InsetsController: onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 73 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(692, 0 - 748, 73), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1440 physicalDisplayHeight=3200 density={2.8125} cutoutSpec={M 0,0 H -9.866666666666667 V 25.86666666666667 H 9.866666666666667 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=68, center=Point(68, 68)}, RoundedCorner{position=TopRight, radius=68, center=Point(1012, 68)}, RoundedCorner{position=BottomRight, radius=68, center=Point(1012, 2332)}, RoundedCorner{position=BottomLeft, radius=68, center=Point(68, 2332)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 73) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[1080,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][1080,107], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false} } host=com.toasterofbread.spmp/com.toasterofbread.spmp.ErrorReportActivity from=android.view.ViewRootImpl.setView:1732
01-20 01:07:59.239 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: setView = com.android.internal.policy.DecorView@dfcb6eb TM=true
01-20 01:07:59.239 28496 28496 I MSHandlerLifeCycle: removeMultiSplitHandler: no exist. decor=DecorView@dfcb6eb[ErrorReportActivity]
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: performTraversals params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   fl=81810100
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   pfl=12020040
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   bhv=DEFAULT
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   fitSides= naviIconColor=0}
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: performTraversals mFirst=true windowShouldResize=true viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f4
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   fl=81810100
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   pfl=12020040
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   bhv=DEFAULT
01-20 01:07:59.254 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]:   fitSides= naviIconColor=0}
01-20 01:07:59.261 28496 28496 D InsetsController: onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 73 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(692, 0 - 748, 73), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1440 physicalDisplayHeight=3200 density={2.8125} cutoutSpec={M 0,0 H -9.866666666666667 V 25.86666666666667 H 9.866666666666667 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=68, center=Point(68, 68)}, RoundedCorner{position=TopRight, radius=68, center=Point(1012, 68)}, RoundedCorner{position=BottomRight, radius=68, center=Point(1012, 2332)}, RoundedCorner{position=BottomLeft, radius=68, center=Point(68, 2332)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 73) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[1080,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][1080,107], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,73], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisibleFrame=[0,1392][1080,2400], mVisible=false, mInsetsRoundedCornerFrame=false} } host=com.toasterofbread.spmp/com.toasterofbread.spmp.ErrorReportActivity from=android.view.ViewRootImpl.relayoutWindow:9802
01-20 01:07:59.262 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
01-20 01:07:59.262 28496 28496 I BLASTBufferQueue: new BLASTBufferQueue, mName= ViewRootImpl@a65bc60[ErrorReportActivity] mNativeObject= 0x7ce78be990 sc.mNativeObject= 0x7c7794c620 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283 
01-20 01:07:59.262 28496 28496 I BLASTBufferQueue: update, w= 1080 h= 2400 mName = ViewRootImpl@a65bc60[ErrorReportActivity] mNativeObject= 0x7ce78be990 sc.mNativeObject= 0x7c7794c620 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 
01-20 01:07:59.262 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=8 res=0x3 s={true 0x7d77a31770} ch=true seqId=0
01-20 01:07:59.262 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0x7d77a31770} hwInitialized=true
01-20 01:07:59.262 28496 28522 D OpenGLRenderer: eglCreateWindowSurface
01-20 01:07:59.264 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
01-20 01:07:59.264 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: Setup new sync id=0
01-20 01:07:59.264 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: Setting syncFrameCallback
01-20 01:07:59.264 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: registerCallbacksForSync syncBuffer=false
01-20 01:07:59.267 28496 28540 I ViewRootImpl@a65bc60[ErrorReportActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
01-20 01:07:59.267 28496 28540 I ViewRootImpl@a65bc60[ErrorReportActivity]: Setting up sync and frameCommitCallback
01-20 01:07:59.270 28496 28522 I BLASTBufferQueue: [ViewRootImpl@a65bc60[ErrorReportActivity]#5](f:0,a:0) onFrameAvailable the first frame is available
01-20 01:07:59.270 28496 28522 I ViewRootImpl@a65bc60[ErrorReportActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
01-20 01:07:59.270 28496 28522 D OpenGLRenderer: CFMS:: SetUp Pid : 28496    Tid : 28522
01-20 01:07:59.271 28496 28522 W Parcel  : Expecting binder but got null!
01-20 01:07:59.271 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: onSyncComplete
01-20 01:07:59.272 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
01-20 01:07:59.272 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0x7ca78ce070
01-20 01:07:59.272 28496 28496 I ViewRootImpl@3c6c15c[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 0
01-20 01:07:59.334 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: MSG_WINDOW_FOCUS_CHANGED 1 0
01-20 01:07:59.334 28496 28496 I ViewRootImpl@a65bc60[ErrorReportActivity]: mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0x7d77a31770}
01-20 01:07:59.334 28496 28496 D InputMethodManager: startInputInner - Id : 0
01-20 01:07:59.334 28496 28496 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus

### SpMp version

0.2.4

### Android version

Android 13

**Comment by toasterofbread** [comment]
This is caused by the same issue as #212, it has nothing to do with offline song playback. Playing songs through other methods should work fine.
