### ISSUE TITLE
[Bug] Discord status Album art doesn't show properly

### ISSUE THREAD

**Issue by meqativ** [toasterofbread/spmp#231]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. log into discord, setup status like you normally would
2. play some track
3. look at the discord status

### Expected behavior

- you can see the thumbnail properly (probably because it was *just* uploaded and discord is ignoring the &ex=&is=&hm= query params)

### Actual behavior

- broken file icon (chrome)
![image](https://github.com/toasterofbread/spmp/assets/106783764/cbb78fab-99f2-4982-8d3c-34aba35df9b5)
- nothing or a white border (firefox)
![firefox](https://github.com/toasterofbread/spmp/assets/106783764/d7e1d51a-a44c-49fb-83df-cffa50f7d050)

### Screenshots / recordings

when u open the image directly
![image](https://github.com/toasterofbread/spmp/assets/106783764/9187432e-b2f0-4f66-b898-be160cf5b746)

### Logs

none, not a crash

### SpMp version

commit 20aa6a4

### Android version

Android 11

### Additional information

to fix it my guess is just pass the &ex=&is=&hm= params with the image link

**Comment by toasterofbread** [comment]
Looks like Discord changed how they handle images, I'll look into fixing this when I can.

**Comment by toasterofbread** [comment]
Fixed in client by bef0044 and in server by https://github.com/toasterofbread/discordimageindex/commit/f15f38582af3ea347930179e9b65346bc771fbdb
