### ISSUE TITLE
[Bug] Log in to youtube dose not change anything in the app the home page is not based on the youtube account and add to history dose not work.

### ISSUE THREAD

**Issue by Exw27** [toasterofbread/spmp#232]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Log in to Youtube
2. Home page is not based on account 

### Expected behavior

The home page should have recommendation based on the youtube account

### Actual behavior

Home page is not based on account 

### Logs

No error logs

### SpMp version

Latest Debug 

### SpMp platform

Android

### OS version

Android 13

**Comment by toasterofbread** [comment]
Are you refreshing the feed manually? And do other things like library content and your profile page appear?

**Comment by Exw27** [comment]
> Are you refreshing the feed manually? And do other things like library content and your profile page appear?

Only my profile photo appears the like library is empty.

**Comment by toasterofbread** [comment]
Are you signing by manually pasting the headers or with the in-app Google login screen?

Also, assuming you haven't already, please try with stable v0.2.4.

**Comment by Exw27** [comment]
> Are you signing by manually pasting the headers or with the in-app Google login screen?
> 
> Also, assuming you haven't already, please try with stable v0.2.4.

I am using the in-app Google login.
And I have tried the stable version with the same issue.

**Comment by Exw27** [comment]
> @Exw27 Can you confirm you've tried this with the latest [nightly build](https://nightly.link/toasterofbread/spmp/workflows/build-android/main)? Also, what model of device are you using?
> 
> Unfortunately problems like this are almost impossible to debug. I've even had one user with two devices say logging in works from one but not the other, no idea why.

I have tried the latest debug version.
I am using a Redmi Note 10S

**Comment by Exw27** [comment]
> Assuming you're using the default (webview) login method, have you tried logging in manually by copying headers from a browser?

This is what I get when login in manually
com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YoutubeChannelNotCreatedException
	at com.toasterofbread.spmp.youtubeapi.impl.youtubemusic.YTMUserAuthStateEndpoint$byHeaders$3.invokeSuspend(YTMUserAuthStateEndpoint.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
