### ISSUE TITLE
Youtube Sign In

### ISSUE THREAD

**Issue by Kabuki1212** [toasterofbread/spmp#233]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Tried To Sign In My Youtube And Theres Alot Of Restart
And Bugs

### Expected behavior

To Work Properly

### Actual behavior

Restarts and Bugs

### Screenshots / recordings

![Screenshot_20240219-011608](https://github.com/toasterofbread/spmp/assets/160406069/b3d5f6e0-c805-4d5b-8684-fc1f5a01bf3c)

### Logs

Youtube Sign In Not Work

### SpMp version

0.2.4

### SpMp platform

Android 12

### OS version

Android 12

### Additional information

Sign in

**Comment by toasterofbread** [comment]
Please provide the entire stack trace

**Comment by Kabuki1212** [comment]
> Please provide the entire stack trace

This Massage always Jumping after im signin to google or playin' songs after im signin in

**Comment by Kabuki1212** [comment]
And Pls Add An Option To Download Playlists With Long Press On Playlist
And Not Download Song After Song

**Comment by toasterofbread** [comment]
Please provide the entire stack trace of the error by copy-pasting it or uploading to paste.ee and pasting the link here

**Comment by toasterofbread** [comment]
The stack trace you screenshotted seems similar to the one in #236, which was triggered by pressing the 'add' button in a playlist page. Are you sure you triggered this by signing in?

**Comment by 0xAissa** [comment]
I'm facing the same issue when logging in.
https://paste.ee/p/Gb3rE
