### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Kabuki1212** [toasterofbread/spmp#234]
Download Full Playlist With Long Press 
Download Button

**Comment by toasterofbread** [comment]
You can download a playlist by selecting all items within the playlist and batch downloading them (there is a select-all button next to the jump arrows)

**Comment by Kabuki1212** [comment]
But Its Not Comfterbole To Download Songs

**Comment by Kabuki1212** [comment]
Maybe Put A Download Button On A Playlist
