### ISSUE TITLE
IndexOutOfBoundsException on local playlist edit

### ISSUE THREAD

**Issue by Kabuki1212** [toasterofbread/spmp#235]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Stack Trace Problem

### Expected behavior

To Work

### Actual behavior

Not Work

### Screenshots / recordings

![Screenshot_20240219-015501](https://github.com/toasterofbread/spmp/assets/160406069/2d204fed-ab01-40ee-b862-b91407cac27c)

### Logs

Not Working

### SpMp version

0.2.4

### SpMp platform

Android 12

### OS version

Android 12

### Additional information

Not Working

**Comment by Kabuki1212** [comment]
https://paste.ee/p/pitnF

**Comment by toasterofbread** [comment]
What exact steps did you take that produced this error? Please don't skip/ignore fields in the issue template.

**Comment by Kabuki1212** [comment]
i just signd in and played music and thats it

**Comment by toasterofbread** [comment]
The stack trace you linked seems to have been triggered by editing a local playlist, is that not what you did?

**Comment by Kabuki1212** [comment]
I Played A Song And Tried To Add 
A Song To A Playlist And Then This Jumped In

**Comment by toasterofbread** [comment]
I've improved the error message given when editing a local playlist fails. Please try again using the same steps and upload the stack trace.

**Comment by toasterofbread** [comment]
I've improved the error message given when editing a local playlist fails. Please download the [latest build](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), then try again using the same steps and upload the stack trace.

**Comment by senolfndk** [comment]
same problem![Screenshot_20240225-000247.jpg](https://github.com/toasterofbread/spmp/assets/52818836/856abfb4-77ea-4a5c-93a0-cc1a2becf7a1)

**Comment by senolfndk** [comment]
crashes when clicking on song

**Comment by toasterofbread** [comment]
@senolfndk Please fill out a new issue

**Comment by toasterofbread** [comment]
@senolfndk Please fill out a new issue
