### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by senolfndk** [toasterofbread/spmp#240]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

I get this error when I click on the song

### Expected behavior

I get this error when I click on the song

### Actual behavior

I get this error when I click on the song

### Screenshots / recordings

![Screenshot_20240225-000247](https://github.com/toasterofbread/spmp/assets/52818836/41fd80fe-a159-483f-bdaa-ad20f39dfe19)

### Logs

I get this error when I click on the song

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

android 12

**Comment by toasterofbread** [comment]
Please provide the full stack trace

**Comment by senolfndk** [comment]
> Lütfen tam yığın izlemeyi sağlayın

I'm not an expert on this subject

**Comment by toasterofbread** [comment]
The text in your screenshot is cut off. Copy-paste the entire text or upload it to paste.ee and paste the link.

**Comment by senolfndk** [comment]
Now I can't click on the song or it doesn't respond.

**Comment by senolfndk** [comment]
It crashes and I can't intervene in any way.

**Comment by senolfndk** [comment]
https://github.com/toasterofbread/spmp/assets/52818836/6e5d87ac-4213-48d5-ab7b-3c17ef2a4d74

**Comment by toasterofbread** [comment]
As said in the issue template, if your issue involves a crash but no logs were displayed, then please find the logs using Logcat or a similar tool such as [this one](https://play.google.com/store/apps/details?id=com.conena.logcat.reader&hl=en_US).

**Comment by senolfndk** [comment]
https://paste.ee/p/mlgvN

**Comment by toasterofbread** [comment]
I've improved the error message for when this occurs. Please try again and paste the error that displays.

**Comment by senolfndk** [comment]
> I've improved the error message for when this occurs. Please try again and paste the error that displays.

https://paste.ee/p/hJ9bp

**Comment by toasterofbread** [comment]
@senolfndk That stack trace seems to be for a completely separate bug (which I'll fix if I can). Are you able to reproduce the original issue?
