### ISSUE TITLE
The cover image is too big

### ISSUE THREAD

**Issue by AozoraDev** [toasterofbread/spmp#245]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open SpMp
2. Click on any song
3. Open player

### Expected behavior

The image should not big?

### Actual behavior

Uhh.... The image is too big?

### Screenshots / recordings

![Screenshot_20240302_112624](https://github.com/toasterofbread/spmp/assets/61007475/b9040f0e-cbcb-4058-a5ac-587d217d3e51)

### Logs

-

### SpMp version

0.3.0

### SpMp platform

Linux

### OS version

Arch Linux

### Additional information

Did you know that every time you breath, you resetting your dying timer.

**Comment by toasterofbread** [comment]
This is an intentional design choice
