### ISSUE TITLE
Stable SpMp version crashes at launch on Linux.

### ISSUE THREAD

**Issue by Yimellovzski** [toasterofbread/spmp#252]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Download the stable release linux version
2. Make it executable & launch it via command line with ./spmp(...).appimage
3. It will prompt a text "Running SpMp..."
4. the program crashes.

### Expected behavior

It should launch just like when using the android version of spmp, I installed all the required dependencies as well (JDK-17, ZeroMQ, libappindicator3, mpv, curl.)

### Actual behavior

After the prompt "Running SpMp..." appears, nothing else happens. However, when running the debug version, it runs fine except the borders are all glitched out just like in this screenshot. (I had to run Spms first before launching the debug version.)

### Logs

No logs appear.

### SpMp version

0.3.0

### SpMp platform

Linux

### OS version

Pop!_OS 22.04 LTS (Ubuntu)

**Comment by toasterofbread** [comment]
Please try the latest build on the main branch, the one in your recording was built on the `layout-customisation` branch (and seems to be working correctly).
