### ISSUE TITLE
UX is very jittery 

### ISSUE THREAD

**Issue by FaqatZubair1** [toasterofbread/spmp#253]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Open the app and navigate through the UI
I have used a lot of ytmusic clients, this is the best in terms of functionality, but at the same time, the animations skip a lot of frames, and my phone is very capable of handling animations. I think you have added a lot of things in the UI. If a few things were made minimalist, it'd make the UX very good

### Expected behavior

Smooth UX

### Actual behavior

Jittery UX

### Logs

NA

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

Android 14

**Comment by toasterofbread** [comment]
Yeah, SpMp doesn't have the best performance in the world, but I don't think the UI is particularly cluttered (certainly not to the point of harming performance). I'm open to specific suggestions on what could be changed without significantly harming functionality, but telling me to make it "more minimalist" isn't very helpful. Also, which specific animations are you talking about?
