### ISSUE TITLE
[Feature] Other lyrics providers

### ISSUE THREAD

**Issue by Matronicz** [toasterofbread/spmp#257]
I feel like KuGou and PetitLyrics arent the best for synced lyrics, as many songs lyrics aren't there or sometimes there is a problem with the font, its all messed up and unreadable. So I feel a great provider would be Musixmatch as its one of the largest lyrics sites, which also contains synced lyrics, and contains almost all songs

**Comment by toasterofbread** [comment]
Musixmatch doesn't seem to offer a free service for synced lyrics, so I won't be adding it.

Don't know what you mean by font issues (or how that would be fixed by using Musixmatch), but there's a decent chance 681905d fixed them.

**Comment by Matronicz** [comment]
![lyrics](https://github.com/toasterofbread/spmp/assets/102349655/069c5900-0ecc-452f-90e0-a389429b7223)
ok so this is an example of what I meant by font issues, I noticed its usually from PetitLyrics, noticed it like just once from KuGou
I'm kind of ok with how it looks, but for word synced, it just doesn't work anymore, instead of words being highlighted, the letters become randomly highlighted and it doesn't work as KuGou line synced.

Sorry for any misunderstanding.
