### ISSUE TITLE
unable to log into accounts due to AccountSwitcherEndpoint not found

### ISSUE THREAD

**Issue by anispwyn** [toasterofbread/spmp#259]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

**you need google account that has youtube brand accounts**

1. go to login page
2. find post request -> copy value -> copy as cURL (POSIX)
3. paste the value
4. error appears

### Expected behavior

AccountSwitcherEndpoint should exist and i will be able to change accounts

### Actual behavior

runtimeException

### Screenshots / recordings

![spmp_a08XQUPzNY](https://github.com/toasterofbread/spmp/assets/36318840/424fbc32-344a-4a50-8b06-a1328c47f552)

### Logs

cant show full logs cuz it has my cookie in it

i can show this atmost
`
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'AccountSwitcherEndpoint' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
`

### SpMp version

commit 668fb70 

### SpMp platform

Windows

### OS version

windows 11 insider preview build: 26080.1 ge_release

### Additional information

:3

**Comment by toasterofbread** [comment]
Should be fixed now
