### ISSUE TITLE
Invisible source files

### ISSUE THREAD

**Issue by mikropsoft** [toasterofbread/spmp#262]
I would like to contribute to the translation. strings.xml file is available. but this part is not visible : shared/src/commonMain/kotlin/com/toasterofbread/spmp/resources/uilocalisation/localised/

and that's all there is in this folder:

![Ekran Görüntüsü (219)](https://github.com/toasterofbread/spmp/assets/75412448/0dd409f4-e756-415a-a99a-484306507662)

**Comment by toasterofbread** [comment]
Thanks, these were recently moved to the ytm-kt repository. You can find them [here](https://github.com/toasterofbread/ytm-kt/tree/main/library/src/commonMain/kotlin/dev/toastbits/ytmkt/uistrings) now. I've updated the wiki page as well.
