### ISSUE TITLE
Desktop Feature: Add back button for settings window

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#267]
I was confused that I thought I had to restart the app every time I wanted change the settings before finding out `esc` was the key to return. It would be convenient to utilize `mouse5` button to `esc` key and a back buttons. 

I also drafted a button placement concept below:
![back button___](https://github.com/toasterofbread/spmp/assets/104473808/52ae04dc-97c6-4869-ab3c-fbe1c275fa43)

I don't have much experience with Material Design but I hope this suggests an alternative way to return to the main page for people who only uses mouse to navigate.

**Comment by toasterofbread** [comment]
Mouse back is already implemented, it just doesn't seem to work on Windows for some reason. This should be fixed when #241 is merged.

In-UI back buttons for subpages are also planned.

**Comment by toasterofbread** [comment]
Navigating back with the mouse (or a custom key) should work now

**Comment by toasterofbread** [comment]
This was implemented by 05e593b
