### ISSUE TITLE
Desktop: WINDOW_TRANSPARENCY makes the spmp invisible on windows 

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#268]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. In spmp: Go to Settings/Theming/Enable window transparency > Enable and set background opacity to 0.8.
![image](https://github.com/toasterofbread/spmp/assets/104473808/1776571a-0af2-406e-8560-eba1c6554e6b)
2. Restart spmp
3. **Oh no**
![image](https://github.com/toasterofbread/spmp/assets/104473808/b43b5e83-5769-4407-9b6c-2fb5935c8b0a)

### Expected behavior

Window transparency should work with specified opacity value.

### Actual behavior

Invisible window. spmp process does show on task bar and in task manager.
![image](https://github.com/toasterofbread/spmp/assets/104473808/fb3cba33-a435-49a1-8e42-e52698117bed)

### Screenshots / recordings

![image](https://github.com/toasterofbread/spmp/assets/104473808/d0cc0ce5-4cd1-4189-813b-93f7cb9b0b9f)
![image](https://github.com/toasterofbread/spmp/assets/104473808/a678d9a7-a6e4-4f0d-be66-e299c2a27374)
![image](https://github.com/toasterofbread/spmp/assets/104473808/f730b2da-5548-44ad-8a54-cc1d4af5e9e8)

### Logs

No logs shown.

### SpMp version

0.3.0

### SpMp platform

Windows

### OS version

Microsoft Windows 10 Home (x64) Build 19045.4170 (22H2)

### Additional information

Going to `AppData\Local\spmp/preferences.json` and removing `"THEME_ENABLE_WINDOW_TRANSPARENCY":true,"THEME_WINDOW_BACKGROUND_OPACITY":0.8039031,` fixes the issue.
![image](https://github.com/toasterofbread/spmp/assets/104473808/68553349-03b2-43cf-ae68-f78c2f9f8480)

I don't think this option should be visible unless it is supported in windows.

**Comment by toasterofbread** [comment]
Thanks, I've hidden the options on Windows for now.
