### ISSUE TITLE
Feature Request: Option to change/swap playback controls in a landscape window

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#270]
An option in settings to change/swap playback controls below the album cover in a landscape window for easy access.

### Concept:
![contp](https://github.com/toasterofbread/spmp/assets/104473808/5b384709-68f7-47af-9614-e2a8c53b88ac)

**Comment by toasterofbread** [comment]
Available as option "Swap controls and song image in landscape player" in the `Player` settings.
