### ISSUE TITLE
Feature Request: Option to adjust app animation speed.

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#271]
Option to adjust app animation speed instead of being dependent on system animation speed. This could help reduce the gesture sensitivity when bringing up the player and the queue and vice versa. 

### Feature inspired by Dantotsu's UI sub-setting:
![image](https://github.com/toasterofbread/spmp/assets/104473808/48b41e8f-7163-4767-80aa-80ec0c6823ed)

**Comment by toasterofbread** [comment]
Do you specifically mean the player expansion animation, or would you want this apply to all animations in the app (not that there are many of them)? I'm also not sure how this would affect the gesture sensitivity of expanding the player.

**Comment by PopCat19** [comment]
All animations

**Comment by toasterofbread** [comment]
Player swipe gesture sensitivity option was added by ee3057f. I won't be adding a global slider though.
