### ISSUE TITLE
Strange behavior when resizing (leaves border, but not resizing actually)

### ISSUE THREAD

**Issue by fedya-eremin** [toasterofbread/spmp#285]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Download latest AppImage from release page
2. Run AppImage as binary
3. Try to resize it with method provided by desktop platform

### Expected behavior

Expectede to resize as it should 

### Actual behavior

Attempts to resize leave black bottom-right background and do not resize app frame, which is anchored to top-left corner. Same behavior in tiling mode

### Screenshots / recordings

![image](https://github.com/toasterofbread/spmp/assets/126074306/ea549cd9-2cee-44d5-9e1f-6e1c8d1c98fc)

### Logs

No logs when resizing

### SpMp version

0.3.1

### SpMp platform

Linux

### OS version

Fedora 39 Sway

### Additional information

Running Wayland & SwayWM

**Comment by toasterofbread** [comment]
I use Wayland and Hyprland myself and I've never seen this happen.

Since this is probably an issue with [Compose Multiplatform](https://github.com/JetBrains/compose-multiplatform) (the UI framework SpMp uses), could you try running one of their [samples](https://github.com/JetBrains/compose-multiplatform/tree/master/examples) to see if they exhibit the same behaviour?

**Comment by fedya-eremin** [comment]
TY, I'll do it

**Comment by fedya-eremin** [comment]
![image](https://github.com/toasterofbread/spmp/assets/126074306/b330dde6-2695-48c4-8b9b-fd0d54879dcb)
Thanks, It also presents in library's examples. Idk if it is an issue of library or sway, but apparently not of an app

**Comment by toasterofbread** [comment]
OK, thanks for checking. If you report the issue to Compose and/or Sway (which I'd encourage), it would be nice if you linked to it here.
