### ISSUE TITLE
Can video playback be supported?

### ISSUE THREAD

**Issue by aikorola** [toasterofbread/spmp#287]
Or provide a solution for playing and downloading videos, thank you!!!

**Comment by toasterofbread** [comment]
Video playback was implemented for desktop in 85eec82. I plan on adding it for Android soon.

**Comment by farzana840** [comment]
> Video playback was implemented for desktop in [85eec82](https://github.com/toasterofbread/spmp/commit/85eec82dbff3dfab8ecf7314f2aa47281abf06da). I plan on adding it for Android soon.

Thank you I was waiting for this feature and it's getting implemented yayy
