### ISSUE TITLE
NullPointerException when trying to play a song from downloaded

### ISSUE THREAD

**Issue by spl3g** [toasterofbread/spmp#290]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Go to downloaded
2. Select a song

### Expected behavior

Plays a song

### Actual behavior

Throws a NullPointerException and freezes the app afterwards.

### Screenshots / recordings

https://github.com/toasterofbread/spmp/assets/58591608/3883bf4d-afce-4027-84f5-a44d0b838e8c

### Logs

---STACK TRACE---
java.lang.NullPointerException
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:31)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:167)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:224)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:83)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
	at android.view.View.dispatchPointerEvent(View.java:15928)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7242)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7032)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9432)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9383)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9352)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9558)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@434a75, androidx.compose.runtime.BroadcastFrameClock@8d48a0a, StandaloneCoroutine{Cancelling}@24a027b, AndroidUiDispatcher@c66b898]

---LOGCAT (last 158 lines)---
--------- beginning of main
04-09 22:41:31.109 27367 27419 D TrafficStats: tagSocket(97) with statsTag=0xffffffff, statsUid=-1
04-09 22:41:31.759 27367 27477 D ProfileInstaller: Skipping profile installation for com.toasterofbread.spmp
04-09 22:41:32.360 27367 27448 D BufferPoolAccessor2.0: bufferpool2 0xb400007c32229408 : 6(49152 size) total buffers - 4(32768 size) used buffers - 4/10 (recycle/alloc) - 1/2 (fetch/transfer)
04-09 22:41:32.360 27367 27448 D BufferPoolAccessor2.0: evictor expired: 1, evicted: 1
04-09 22:41:33.316 27367 27431 D TrafficStats: tagSocket(103) with statsTag=0xffffffff, statsUid=-1
04-09 22:41:56.539 27367 27458 I SpMp    : savePersistentQueue: Saved 1 songs with data PersistentQueueMetadata(song_index=0, position_ms=136449)
04-09 22:42:24.237 27367 27449 D BufferPoolAccessor2.0: bufferpool2 0xb400007c32229408 : 4(32768 size) total buffers - 4(32768 size) used buffers - 4/10 (recycle/alloc) - 1/2 (fetch/transfer)
04-09 22:42:26.547 27367 27433 I SpMp    : savePersistentQueue: Saved 1 songs with data PersistentQueueMetadata(song_index=0, position_ms=136449)
04-09 22:42:28.971 27367 27378 I terofbread.spmp: Background concurrent mark compact GC freed 3055529(92MB) AllocSpace objects, 92(2552KB) LOS objects, 69% free, 42MB/138MB, paused 5.138ms,12.752ms total 331.736ms
04-09 22:42:29.239 27367 27448 D BufferPoolAccessor2.0: bufferpool2 0xb400007c32229408 : 4(32768 size) total buffers - 4(32768 size) used buffers - 4/10 (recycle/alloc) - 1/2 (fetch/transfer)
04-09 22:42:29.239 27367 27448 D BufferPoolAccessor2.0: evictor expired: 1, evicted: 1
04-09 22:42:46.797 27367 27367 W System.err: java.lang.NullPointerException
04-09 22:42:46.798 27367 27367 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
04-09 22:42:46.798 27367 27367 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
04-09 22:42:46.798 27367 27367 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:31)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:167)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:224)
04-09 22:42:46.798 27367 27367 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:83)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
04-09 22:42:46.798 27367 27367 W System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
04-09 22:42:46.798 27367 27367 W System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4403)
04-09 22:42:46.798 27367 27367 W System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.View.dispatchPointerEvent(View.java:15928)
04-09 22:42:46.798 27367 27367 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7242)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7032)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9432)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9383)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9352)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9558)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.os.Looper.loopOnce(Looper.java:162)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.os.Looper.loop(Looper.java:294)
04-09 22:42:46.799 27367 27367 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8194)
04-09 22:42:46.799 27367 27367 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 22:42:46.800 27367 27367 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-09 22:42:46.800 27367 27367 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
04-09 22:42:46.800 27367 27367 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@434a75, androidx.compose.runtime.BroadcastFrameClock@8d48a0a, StandaloneCoroutine{Cancelling}@24a027b, AndroidUiDispatcher@c66b898]
04-09 22:42:46.828 27367 27367 W SQLiteLog: (28) double-quoted string literal: "version"
04-09 22:42:46.828 27367 27367 W SQLiteLog: (28) double-quoted string literal: "Version"
04-09 22:42:46.828 27367 27367 I System.out: Database is already up to date (version 5)
04-09 22:42:46.830 27367 27948 I System.out: Retrieving logcat output...

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android 14

### Additional information

The same thing happens on pc

**Comment by suhan-paradkar** [comment]
I don't know, but maybe related...
Downloading a song produces this 
```
---STACK TRACE---
java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of 'android.app.Service' appears in /system/framework/framework.jar)
	at androidx.tracing.Trace$$ExternalSyntheticApiModelOutline0.m(SourceFile:17)
	at com.toasterofbread.spmp.platform.download.PlayerDownloadService$SongDownloaderImpl.onFirstDownloadStarting(Unknown Source:72)
	at com.toasterofbread.spmp.platform.download.SongDownloader$startDownload$2.invokeSuspend(SourceFile:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:99)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b1de73f, Dispatchers.Default]

---LOGCAT (last 110 lines)---
04-15 20:38:17.259 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.260 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.260 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.265 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.272 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.274 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.275 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.275 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.279 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 450 capacity
04-15 20:38:17.282 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.288 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.292 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.292 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.292 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.298 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.302 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 2190 capacity
04-15 20:38:17.305 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.308 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.308 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.309 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.315 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.322 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.325 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.326 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.326 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.332 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.338 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.342 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.342 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.342 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.348 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.355 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.359 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.360 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.360 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.365 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.372 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.375 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.376 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.376 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.380 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 450 capacity
04-15 20:38:17.382 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.389 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.392 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.393 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.393 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.399 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.402 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 2190 capacity
04-15 20:38:17.405 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.408 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.409 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.409 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.415 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.422 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.426 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.427 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.427 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.432 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.439 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.442 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.443 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.443 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.449 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.456 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.461 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.461 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.461 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.467 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.472 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.475 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.476 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.476 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.482 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 450 capacity
04-15 20:38:17.483 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.489 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.493 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.493 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.494 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.499 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.503 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 2190 capacity
04-15 20:38:17.506 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.508 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.509 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.509 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.516 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.522 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.526 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.527 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.527 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.533 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.539 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.542 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.543 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.543 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.549 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.556 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.560 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.561 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.561 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.566 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.573 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.576 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.576 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.577 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
04-15 20:38:17.583 14562 14562 D Parcel  : Parcel 0x79d4cb4cd0: freeing with 450 capacity
04-15 20:38:17.588 14562 14581 D Parcel  : Parcel 0x79bc799b50: freeing with 258 capacity
04-15 20:38:17.589 14562 14562 D Parcel  : Parcel 0x7fc5cd34d0: freeing with 120 capacity
04-15 20:38:17.593 14562 14581 D Parcel  : Parcel 0x79bc799b60: freeing with 120 capacity
04-15 20:38:17.594 14562 14581 D Parcel  : Parcel 0x79bc799f50: freeing with 120 capacity
04-15 20:38:17.594 14562 14581 D Parcel  : Parcel 0x79bc799ea0: freeing with 120 capacity
```

It also produces an empty file but the download doesn't start

Android 9
OPPO A12(CPH2083)

**Comment by LockFlip** [comment]
What is the solution for the problem, I am having the same problem of when I try to play a downloaded song, it won't play and give me the same error

**Comment by toasterofbread** [comment]
@LockFlip What commit are you using?

**Comment by LockFlip** [comment]
> @LockFlip What commit are you using?

Android 14
OnePlus 11R
SpMp version: 0.3.2

**Comment by toasterofbread** [comment]
@LockFlip The commit that fixes this has not been included in a stable release yet

**Comment by LockFlip** [comment]
> @LockFlip The commit that fixes this has not been included in a stable release yet

Oh ok, when can I expect it to be realised?

**Comment by toasterofbread** [comment]
@LockFlip Soon™
