### ISSUE TITLE
Can't play downloaded songs 

### ISSUE THREAD

**Issue by Kails0** [toasterofbread/spmp#294]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Go to the downloaded songs menu
2. Select a song

### Expected behavior

after a downloaded song is selected it should play

### Actual behavior

gives error log and the program stops and needs to be force closed

### Logs

---STACK TRACE---
java.lang.NullPointerException
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:31)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:167)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:224)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:83)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@6c88e7b, androidx.compose.runtime.BroadcastFrameClock@cf05498, StandaloneCoroutine{Cancelling}@1aa84f1, AndroidUiDispatcher@d8238d6]

---LOGCAT (last 158 lines)---
04-21 14:22:18.968 14560 14560 W System.err: 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
04-21 14:22:18.968 14560 14560 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
04-21 14:22:18.968 14560 14560 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:224)
04-21 14:22:18.968 14560 14560 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:83)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:22:18.968 14560 14560 W System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
04-21 14:22:18.968 14560 14560 W System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
04-21 14:22:18.968 14560 14560 W System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.View.dispatchPointerEvent(View.java:15309)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
04-21 14:22:18.968 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.os.Looper.loopOnce(Looper.java:161)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.os.Looper.loop(Looper.java:288)
04-21 14:22:18.969 14560 14560 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
04-21 14:22:18.969 14560 14560 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 14:22:18.969 14560 14560 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-21 14:22:18.969 14560 14560 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
04-21 14:22:18.969 14560 14560 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@d2055b3, androidx.compose.runtime.BroadcastFrameClock@c533770, StandaloneCoroutine{Cancelling}@af2eae9, AndroidUiDispatcher@637336e]
04-21 14:22:19.013 14560 14560 W SQLiteLog: (28) double-quoted string literal: "version"
04-21 14:22:19.013 14560 14560 W SQLiteLog: (28) double-quoted string literal: "Version"
04-21 14:22:19.014 14560 14560 I System.out: Database is already up to date (version 5)
04-21 14:22:19.016 14560 14629 I System.out: Retrieving logcat output...
04-21 14:22:19.024 14560 14580 W Parcel  : Expecting binder but got null!
04-21 14:22:19.033 14560 14560 D AutofillManager: Fill dialog is enabled:false, hints=[]
04-21 14:22:19.050 14560 14580 E OpenGLRenderer: Unable to match the desired swap behavior.
04-21 14:22:21.800 14560 14571 I terofbread.spmp: Background concurrent copying GC freed 963959(32MB) AllocSpace objects, 165(9232KB) LOS objects, 75% free, 11MB/46MB, paused 76us,40us total 147.635ms
04-21 14:22:33.277 14560 14619 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10245; state: ENABLED
04-21 14:23:59.852 14560 14580 E OpenGLRenderer: Unable to match the desired swap behavior.
04-21 14:24:26.665 14560 14580 E OpenGLRenderer: Unable to match the desired swap behavior.
04-21 14:24:38.995 15357 15357 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10245; state: ENABLED
04-21 14:24:39.057 15357 15357 V GraphicsEnvironment: ANGLE Developer option for 'com.toasterofbread.spmp' set to: 'default'
04-21 14:24:39.057 15357 15357 V GraphicsEnvironment: ANGLE GameManagerService for com.toasterofbread.spmp: false
04-21 14:24:39.057 15357 15357 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
04-21 14:24:39.058 15357 15357 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-21 14:24:39.059 15357 15357 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-21 14:24:39.075 15357 15357 W SQLiteLog: (28) double-quoted string literal: "version"
04-21 14:24:39.076 15357 15357 W SQLiteLog: (28) double-quoted string literal: "Version"
04-21 14:24:39.076 15357 15357 I System.out: Database is already up to date (version 5)
04-21 14:24:39.078 15357 15357 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
04-21 14:24:39.078 15357 15357 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
04-21 14:24:39.079 15357 15357 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
04-21 14:24:39.104 15357 15357 I System.out: Loading resource file at values/strings.xml
04-21 14:24:39.117 15357 15357 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10245; state: DISABLED
04-21 14:24:39.120 15357 15374 W Parcel  : Expecting binder but got null!
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: QUALCOMM build                   : 8382da08aa, I139f36ad46
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: Build Date                       : 02/18/22
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.11
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: Local Branch                     : 
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: Remote Branch                    : 
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: Remote Branch                    : 
04-21 14:24:39.154 15357 15374 I AdrenoGLES-0: Reconstruct Branch               : 
04-21 14:24:39.155 15357 15374 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
04-21 14:24:39.155 15357 15374 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
04-21 14:24:39.159 15357 15374 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
04-21 14:24:39.182 15357 15374 E OpenGLRenderer: Unable to match the desired swap behavior.
04-21 14:24:39.191 15357 15387 I Gralloc4: Adding additional valid usage bits: 0x8202000
04-21 14:24:39.274 15357 15357 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10245; state: ENABLED
04-21 14:24:45.074 15357 15460 D ProfileInstaller: Skipping profile installation for com.toasterofbread.spmp
04-21 14:24:49.599 15357 15367 I terofbread.spmp: Background concurrent copying GC freed 604502(20MB) AllocSpace objects, 55(2892KB) LOS objects, 75% free, 9192KB/35MB, paused 82us,43us total 125.914ms
04-21 14:25:08.390 15357 15450 D TrafficStats: tagSocket(90) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.390 15357 15427 D TrafficStats: tagSocket(105) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.394 15357 15440 D TrafficStats: tagSocket(129) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.394 15357 15412 D TrafficStats: tagSocket(131) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.394 15357 15418 D TrafficStats: tagSocket(130) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.396 15357 15437 D TrafficStats: tagSocket(83) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.398 15357 15454 D TrafficStats: tagSocket(120) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:08.398 15357 15442 D TrafficStats: tagSocket(102) with statsTag=0xffffffff, statsUid=-1
04-21 14:25:11.719 15357 15357 W System.err: java.lang.NullPointerException
04-21 14:25:11.719 15357 15357 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:138)
04-21 14:25:11.719 15357 15357 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:45)
04-21 14:25:11.719 15357 15357 W System.err: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SourceFile:51)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(Unknown Source:31)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Unknown Source:4)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Unknown Source:4)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:167)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:146)
04-21 14:25:11.719 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:30)
04-21 14:25:11.720 15357 15357 W System.err: 	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:122)
04-21 14:25:11.720 15357 15357 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(SourceFile:79)
04-21 14:25:11.720 15357 15357 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(SourceFile:224)
04-21 14:25:11.720 15357 15357 W System.err: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:83)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
04-21 14:25:11.720 15357 15357 W System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
04-21 14:25:11.720 15357 15357 W System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
04-21 14:25:11.720 15357 15357 W System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.View.dispatchPointerEvent(View.java:15309)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
04-21 14:25:11.720 15357 15357 W System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.os.Looper.loopOnce(Looper.java:161)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.os.Looper.loop(Looper.java:288)
04-21 14:25:11.721 15357 15357 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
04-21 14:25:11.721 15357 15357 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 14:25:11.721 15357 15357 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-21 14:25:11.721 15357 15357 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
04-21 14:25:11.721 15357 15357 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@6c88e7b, androidx.compose.runtime.BroadcastFrameClock@cf05498, StandaloneCoroutine{Cancelling}@1aa84f1, AndroidUiDispatcher@d8238d6]
04-21 14:25:11.758 15357 15357 W SQLiteLog: (28) double-quoted string literal: "version"
04-21 14:25:11.758 15357 15357 W SQLiteLog: (28) double-quoted string literal: "Version"
04-21 14:25:11.759 15357 15357 I System.out: Database is already up to date (version 5)
04-21 14:25:11.763 15357 15410 I System.out: Retrieving logcat output...
04-21 14:25:11.780 15357 15374 W Parcel  : Expecting binder but got null!
04-21 14:25:11.796 15357 15357 D AutofillManager: Fill dialog is enabled:false, hints=[]
04-21 14:25:11.813 15357 15374 E OpenGLRenderer: Unable to match the desired swap behavior.

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android 13

**Comment by toasterofbread** [comment]
That's strange, this should've been fixed by c087cf57d445dffb642b351c9733583a743a3cc3. Which commit did you test?
