### ISSUE TITLE
Error encountered while attempting to download a song

### ISSUE THREAD

**Issue by Matytoonist** [toasterofbread/spmp#295]
### Checklist

- [x] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Select song
2. Menu -> download -> to library/custom path (happens with both)

### Expected behavior

Song should download

### Actual behavior

Error message with stack trace log and no song downloaded

### Screenshots / recordings

https://file.garden/ZHiIgOH23R-SBqSb/recording.mp4

### Logs

---STACK TRACE---
java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of '[android.app](http://android.app/).Service' appears in /system/framework/framework.jar)
at androidx.tracing.Trace$$ExternalSyntheticApiModelOutline0.m(SourceFile:17)
at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).PlayerDownloadService$SongDownloaderImpl.onFirstDownloadStarting(Unknown Source:72)
at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).SongDownloader$startDownload$2.invokeSuspend(SourceFile:97)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
at [androidx.fragment.app](http://androidx.fragment.app/).Fragment$[4.run](http://4.run/)(SourceFile:105)
at [kotlinx.coroutines.scheduling.TaskImpl.run](http://kotlinx.coroutines.scheduling.taskimpl.run/)(Unknown Source:2)
at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f6d52cb, Dispatchers.Default]

---LOGCAT (last 110 lines)---
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [androidx.fragment.app](http://androidx.fragment.app/).Fragment$[4.run](http://4.run/)(SourceFile:105)
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [kotlinx.coroutines.scheduling.TaskImpl.run](http://kotlinx.coroutines.scheduling.taskimpl.run/)(Unknown Source:2)
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
04-25 08:44:27.511 13860 13860 E AndroidRuntime: Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [android.media](http://android.media/).MediaMetadataRetriever.setDataSource(Native Method)
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [android.media](http://android.media/).MediaMetadataRetriever.setDataSource([MediaMetadataRetriever.java:139](http://mediametadataretriever.java:139/))
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [android.media](http://android.media/).MediaMetadataRetriever.setDataSource([MediaMetadataRetriever.java:183](http://mediametadataretriever.java:183/))
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invokeSuspend(SourceFile:31)
04-25 08:44:27.511 13860 13860 E AndroidRuntime: 	... 12 more
04-25 08:50:28.305 15893 15926 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
04-25 08:50:28.305 15893 15926 E AndroidRuntime: Process: com.toasterofbread.spmp, PID: 15893
04-25 08:50:28.305 15893 15926 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of '[android.app](http://android.app/).Service' appears in /system/framework/framework.jar)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at androidx.tracing.Trace$$ExternalSyntheticApiModelOutline0.m(SourceFile:17)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).PlayerDownloadService$SongDownloaderImpl.onFirstDownloadStarting(Unknown Source:72)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).SongDownloader$startDownload$2.invokeSuspend(SourceFile:97)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at [androidx.fragment.app](http://androidx.fragment.app/).Fragment$[4.run](http://4.run/)(SourceFile:105)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at [kotlinx.coroutines.scheduling.TaskImpl.run](http://kotlinx.coroutines.scheduling.taskimpl.run/)(Unknown Source:2)
04-25 08:50:28.305 15893 15926 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
04-25 08:50:42.114 15893 15911 E AndroidRuntime: Process: com.toasterofbread.spmp, PID: 15893
04-25 08:50:42.114 15893 15911 E AndroidRuntime: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at android.widget.Toast$TN.([Toast.java:414](http://toast.java:414/))
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at android.widget.Toast.([Toast.java:119](http://toast.java:119/))
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at android.widget.Toast.makeText([Toast.java:287](http://toast.java:287/))
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at android.widget.Toast.makeText([Toast.java:277](http://toast.java:277/))
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at com.toasterofbread.composekit.platform.PlatformContext.sendToast(SourceFile:15)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at com.toasterofbread.composekit.platform.PlatformContext.sendToast$default(Unknown Source:7)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at com.toasterofbread.spmp.ErrorReportActivity$ErrorDisplay$1$1$3$1$1.invokeSuspend(SourceFile:118)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:50:42.114 15893 15911 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
04-25 08:50:45.920 15893 15933 E AndroidRuntime: Process: com.toasterofbread.spmp, PID: 15893
04-25 08:50:45.920 15893 15933 E AndroidRuntime: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at android.widget.Toast$TN.([Toast.java:414](http://toast.java:414/))
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at android.widget.Toast.([Toast.java:119](http://toast.java:119/))
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at android.widget.Toast.makeText([Toast.java:287](http://toast.java:287/))
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at android.widget.Toast.makeText([Toast.java:277](http://toast.java:277/))
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at com.toasterofbread.composekit.platform.PlatformContext.sendToast(SourceFile:15)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at com.toasterofbread.composekit.platform.PlatformContext.sendToast$default(Unknown Source:7)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at com.toasterofbread.spmp.ErrorReportActivity$ErrorDisplay$1$1$3$1$1.invokeSuspend(SourceFile:118)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:50:45.920 15893 15933 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
--------- beginning of main
04-25 08:56:27.177 16673 16673 V MediaRouter: Adding route: RouteInfo{ name=Dispositivo, description=null, status=null, category=RouteCategory{ name=Sistema types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-25 08:56:27.189 16673 16673 V MediaRouter: Selecting route: RouteInfo{ name=Dispositivo, description=null, status=null, category=RouteCategory{ name=Sistema types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
04-25 08:56:27.861 16673 16712 I SpMp    : savePersistentQueue: Saved 13 songs with data PersistentQueueMetadata(song_index=12, position_ms=263566)
04-25 08:56:29.156 16673 16720 I System.out: Loading stream format for song zA3RjXVQQfk
04-25 08:56:29.464 16673 16720 W System.err: io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class zmq.Msg$1 (Kotlin reflection is not available)' but was 'class [io.ktor.utils.io](http://io.ktor.utils.io/).ByteBufferChannel (Kotlin reflection is not available)'
04-25 08:56:29.465 16673 16720 W System.err: In response from  https://pipedapi.kavin.rocks/streams/zA3RjXVQQfk 
04-25 08:56:29.465 16673 16720 W System.err: Response status  403 Forbidden 
04-25 08:56:29.465 16673 16720 W System.err: Response header  ContentType: text/html; charset=UTF-8 
04-25 08:56:29.465 16673 16720 W System.err: Request header  Accept: application/json 
04-25 08:56:29.465 16673 16720 W System.err:
04-25 08:56:29.465 16673 16720 W System.err: You can read how to resolve NoTransformationFoundException at FAQ:
04-25 08:56:29.465 16673 16720 W System.err: https://ktor.io/docs/faq.html#no-transformation-found-exception
04-25 08:56:29.465 16673 16720 W System.err: 	at io.ktor.client.call.HttpClientCall.bodyNullable(SourceFile:227)
04-25 08:56:29.465 16673 16720 W System.err: 	at dev.toastbits.ytmkt.formats.PipedVideoFormatsEndpoint.getVideoFormats-0E7RQCE(SourceFile:148)
04-25 08:56:29.465 16673 16720 W System.err: 	at dev.toastbits.ytmkt.formats.PipedVideoFormatsEndpoint$getVideoFormats$1.invokeSuspend(SourceFile:13)
04-25 08:56:29.465 16673 16720 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:56:29.465 16673 16720 W System.err: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:56:29.465 16673 16720 W System.err: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:159)
04-25 08:56:29.465 16673 16720 W System.err: 	at okio.Okio.runBlocking(SourceFile:101)
04-25 08:56:29.465 16673 16720 W System.err: 	at okio.Okio.runBlocking$default(SourceFile:3)
04-25 08:56:29.465 16673 16720 W System.err: 	at com.toasterofbread.spmp.platform.playerservice.PlatformPlayerService.createDataSourceFactory$lambda$6(Unknown Source:16)
04-25 08:56:29.465 16673 16720 W System.err: 	at com.toasterofbread.spmp.platform.playerservice.PlatformPlayerService.$r8$lambda$0pM3BbnGNY46zMdII2l_7Z6Jcn8(SourceFile:1)
04-25 08:56:29.465 16673 16720 W System.err: 	at androidx.media3.datasource.ResolvingDataSource.open(Unknown Source:6)
04-25 08:56:29.465 16673 16720 W System.err: 	at androidx.media3.datasource.StatsDataSource.open(SourceFile:10)
04-25 08:56:29.465 16673 16720 W System.err: 	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(SourceFile:26)
04-25 08:56:29.465 16673 16720 W System.err: 	at androidx.media3.exoplayer.upstream.Loader$[LoadTask.run](http://loadtask.run/)(Unknown Source:40)
04-25 08:56:29.465 16673 16720 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1162](http://threadpoolexecutor.java:1162/))
04-25 08:56:29.465 16673 16720 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:636](http://threadpoolexecutor.java:636/))
04-25 08:56:29.465 16673 16720 W System.err: 	at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:764](http://thread.java:764/))
04-25 08:56:29.800 16673 16683 I zygote  : Background concurrent copying GC freed 645893(19MB) AllocSpace objects, 48(3MB) LOS objects, 35% free, 43MB/67MB, paused 246us total 302.810ms
04-25 08:56:31.145 16673 16692 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [576x778]-format:1
04-25 08:56:31.153 16673 16673 D Compose Focus: Owner FocusChanged(true)
04-25 08:56:31.236 16673 16692 W libEGL  : EGLNativeWindowType 0xc4a54008 disconnect failed
04-25 08:56:31.237 16673 16692 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [576x774]-format:1
04-25 08:56:36.573 16673 16692 W libEGL  : EGLNativeWindowType 0xc4a54008 disconnect failed
04-25 08:56:36.637 16673 16673 I System.out: Database is already up to date (version 5)
04-25 08:56:36.669 16673 16673 E ViewRootImpl: sendUserActionEvent() returned.
04-25 08:56:36.743 16673 16689 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
04-25 08:56:36.743 16673 16689 E AndroidRuntime: Process: com.toasterofbread.spmp, PID: 16673
04-25 08:56:36.743 16673 16689 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of '[android.app](http://android.app/).Service' appears in /system/framework/framework.jar)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at androidx.tracing.Trace$$ExternalSyntheticApiModelOutline0.m(SourceFile:17)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).PlayerDownloadService$SongDownloaderImpl.onFirstDownloadStarting(Unknown Source:72)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).SongDownloader$startDownload$2.invokeSuspend(SourceFile:97)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at [androidx.fragment.app](http://androidx.fragment.app/).Fragment$[4.run](http://4.run/)(SourceFile:105)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at [kotlinx.coroutines.scheduling.TaskImpl.run](http://kotlinx.coroutines.scheduling.taskimpl.run/)(Unknown Source:2)
04-25 08:56:36.743 16673 16689 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
04-25 08:56:36.745 16673 16689 W System.err: java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of '[android.app](http://android.app/).Service' appears in /system/framework/framework.jar)
04-25 08:56:36.746 16673 16689 W System.err: 	at androidx.tracing.Trace$$ExternalSyntheticApiModelOutline0.m(SourceFile:17)
04-25 08:56:36.746 16673 16689 W System.err: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).PlayerDownloadService$SongDownloaderImpl.onFirstDownloadStarting(Unknown Source:72)
04-25 08:56:36.746 16673 16689 W System.err: 	at [com.toasterofbread.spmp.platform.download](http://com.toasterofbread.spmp.platform.download/).SongDownloader$startDownload$2.invokeSuspend(SourceFile:97)
04-25 08:56:36.746 16673 16689 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
04-25 08:56:36.746 16673 16689 W System.err: 	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(Unknown Source:107)
04-25 08:56:36.746 16673 16689 W System.err: 	at [androidx.fragment.app](http://androidx.fragment.app/).Fragment$[4.run](http://4.run/)(SourceFile:105)
04-25 08:56:36.746 16673 16689 W System.err: 	at [kotlinx.coroutines.scheduling.TaskImpl.run](http://kotlinx.coroutines.scheduling.taskimpl.run/)(Unknown Source:2)
04-25 08:56:36.746 16673 16689 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(SourceFile:99)
04-25 08:56:36.747 16673 16689 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f6d52cb, Dispatchers.Default]
04-25 08:56:36.935 16673 16673 I System.out: Database is already up to date (version 5)
04-25 08:56:36.939 16673 16723 I System.out: Retrieving logcat output...
04-25 08:56:36.982 16673 16673 I zygote  : Deoptimizing int android.text.Layout.getLineAscent(int) due to JIT inline cache
04-25 08:56:37.000 16673 16692 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
04-25 08:56:37.003 16673 16673 D Compose Focus: Owner FocusChanged(true)

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android GO 8.1.0

### Additional information

* Phone model: Samsung J2 Core
* SpMp library is located on the phone's SD card (external storage)

**Comment by toasterofbread** [comment]
This should be fixed by 0b63e31
