### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [toasterofbread/spmp#298]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6737549200

I'll get a diff soon

### Expected behavior

-

### Actual behavior

-

### Logs

-

### SpMp version

0.3.2 (13)

### SpMp platform

Android

### OS version

-

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/51e0ac2a4136192663272dfbd75f0fe804238ee8

**Comment by toasterofbread** [comment]
Thanks for letting me know, I will look into this.

**Comment by licaon-kter** [comment]
Diff log:  [spmp13.log](https://github.com/toasterofbread/spmp/files/15148388/spmp13.log)

**Comment by toasterofbread** [comment]
@licaon-kter I've updated the APKs on the existing release and checked them against the one from F-Droid. Is there anything I need to do on my end to re-enable the build?

**Comment by licaon-kter** [comment]
No, we're going to retest and reenable if ok, asap :)

**Comment by licaon-kter** [comment]
that's better, thanks, https://gitlab.com/fdroid/fdroiddata/-/commit/ab6d7cba415f4971af1b1e7135ba77f99ae372e3

what was the fix?

**Comment by toasterofbread** [comment]
Thanks. I may or may not have accidentally signed with some debug keys. Not sure if that was the only cause, but either way I recompiled with the right keys and it matched.
