### ISSUE TITLE
Getting `Looper.prepare()` error on downloaded music menu

### ISSUE THREAD

**Issue by artiekra** [toasterofbread/spmp#307]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Download .apk from https://nightly.link/toasterofbread/spmp/workflows/build-android/main (release version) - the error pops up on the fresh install, but after that, I couldn't replicate it.
2. Download a song from context menu (`...`) - logging in seems to not make any difference.
3. Go to the song library, second tab on the top.
4. Use UI at the bottom to switch (quickly?) between downloaded and liked music.

### Expected behavior

SpMp would switch between two menus - one with downloaded music, another with liked songs.

### Actual behavior

After a few presses, described error pops up. Even before the error, instead of reliably showing the music, sometimes the list of downloaded songs would be empty. Uploading to `paste.ee` fails too, instead the same error occurs again.

### Screenshots / recordings

https://github.com/toasterofbread/spmp/assets/115405408/35220f4a-1860-4468-8f2f-4d0c851103aa

### Logs

https://paste.ee/p/Hos78

### SpMp version

SpMp non-release build on 837643d and API version 2

### SpMp platform

Android

### OS version

Android 9

### Additional information

Additionally, after switching between "Downloaded" and "Liked" music a lot of times, a search bar pops up at the bottom. Is it supposed to be like that?

**Comment by artiekra** [comment]
Im also getting the same error, when trying to download  a song. That is:
1. Open a song, press "Download"
2. Wait until it fully downloads
3. This error pops up. Must not that i can just close that error, the song is downloaded anyway, and i can play it.

**Comment by toasterofbread** [comment]
The `Looper.prepare()`-related issues should be fixed now
