### ISSUE TITLE
Shuffle Function 

### ISSUE THREAD

**Issue by kyungrie** [toasterofbread/spmp#311]
The shuffle function only works if the song being played is at the top of the queue. This happens in spmp latest version of android

**Comment by toasterofbread** [comment]
I'm not sure what you mean by this and can't reproduce. Could you please provide more specific information? A screen recording would be ideal.

Also, please confirm you've tested this on the [latest nightly build](https://github.com/toasterofbread/spmp/actions/runs/9700144980).
