### ISSUE TITLE
Show repeat and shuffle buttons in player does not show shuffle & artist not centered

### ISSUE THREAD

**Issue by looowizz** [toasterofbread/spmp#314]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Turn on "Show repeat and shuffle buttons in player" in Player settings
2. Navigate to the player

### Expected behavior

The artist name should be kept centered and the shuffle button should be shown

### Actual behavior

The shuffle button is not shown and artist name is shifted right

### Screenshots / recordings

![Screenshot_20240611-091551](https://github.com/toasterofbread/spmp/assets/47942583/d36bb336-9ebb-4d9a-91aa-69902ebcff54)

### Logs

[SpMp%20log%20c1195acfc109.txt](https://github.com/user-attachments/files/15784801/SpMp.20log.20c1195acfc109.txt)

### SpMp version

0.3.2

### SpMp platform

Android

### OS version

Android 14, GrapheneOS 2024060500

**Comment by toasterofbread** [comment]
The first close-reopen was a misclick, the second was me typing the wrong issue ID for a commit. Sorry for any disturbance :sweat_smile:.
