### ISSUE TITLE
[Feature Request] Hiragana/Katakana/Kanji to Romaji

### ISSUE THREAD

**Issue by Kanna-P** [toasterofbread/spmp#315]
There are some people who just can sing japanese but can't read it (ex: me). I've been wanting this for a long time on any app now

**Comment by Kanna-P** [comment]
Also consider a lyric translator for the people out there and make synced lyrics clickable so it will seek to that specific time it says the lyric

**Comment by JoceMC** [comment]
> Also consider a lyric translator for the people out there and make synced lyrics clickable so it will seek to that specific time it says the lyric

This seems an old feature request but I'd like to see this clickable synced lyrics just like in YouTube Music. It will be really useful so we can stop scrolling through the seekbar to find the specific timestamps for lyrics. 😁
