### ISSUE TITLE
Doesn't work properly in landscape mode (android)

### ISSUE THREAD

**Issue by i00** [toasterofbread/spmp#323]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Open the player in landscape mode.
Some screens are cut off by the notification bar, others are not and the queue cannot be opened.

### Expected behavior

The player should work perfectly in landscape mode as it does in portrait

### Actual behavior

Interface elements are blocked or do not respond to touches 

### Logs

N/A

### SpMp version

0.3.2

### SpMp platform

Android

### OS version

Android 12

**Comment by toasterofbread** [comment]
Could you be more specific please? Screenshots would help. 

Also, is the behaviour consistent between v0.3.2 and `main`? Some fairly major changes have been made to the layout of the player (and the app overall).
