### ISSUE TITLE
[Feature Request] Chinese Traditional data source

### ISSUE THREAD

**Issue by null-von-sushi** [toasterofbread/spmp#325]
Currently the app is missing data source for ZH_TW / traditional Chinese. Please would you be so kind as to add it? 
Thank you.

**Comment by toasterofbread** [comment]
What do you mean by data source? If you just mean string localisations, they were added in #300 and will be in v0.4.0.

**Comment by null-von-sushi** [comment]
My apologies, I somehow missed that. 
I was talking about the option in `Settings` -> `Data language`. I was under the impression that this was responsible for what language song names will be in (YouTube website likes to translate them randomly)?

**Comment by toasterofbread** [comment]
That will be available in v0.4.0 along with the string localisations.
