### ISSUE TITLE
Youtube parser fails to load on app relaunch

### ISSUE THREAD

**Issue by talkingkittycat** [toasterofbread/spmp#327]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Launch app
2. Close app
3. Launch app again

### Expected behavior

Youtube feed loads as normal

### Actual behavior

Error message loads and feed has to be manually refreshed

### Screenshots / recordings

https://github.com/toasterofbread/spmp/assets/8497326/3217d3b7-019d-4384-853f-929ee2dce2b1

### Logs

https://paste.ee/p/MyZMj

### SpMp version

5e6ed9c 

### SpMp platform

Android

### OS version

LineageOS 21 (Based on Android 14)

**Comment by toasterofbread** [comment]
This was probably caused by switching between versions. Have you tried cleared the app's data?

**Comment by talkingkittycat** [comment]
This seems to have fixed the issue, thank you!
