### ISSUE TITLE
Can we fetch songs from the device

### ISSUE THREAD

**Issue by Raghucharan16** [toasterofbread/spmp#333]
I run into poor network all the time so it is preferable if app takes permission from local device and is allowed to play songs without internet connection (offline). (You gave an option to download to a custom path right that is very cool).
And Thanks for this amazing work.

**Comment by toasterofbread** [comment]
SpMp already supports downloading songs for offline playback. Could you be more specific about what it is you'd want added/changed?

**Comment by Raghucharan16** [comment]
Yes, what I meant to say is, it would be a good feature if the app asks permission for storage & media and can able play songs from device. As of now, it won't take any permissions so, as can download the songs to any folder, if it can access the whole device, then it can fetch all the media right?

**Comment by toasterofbread** [comment]
I'm still not entirely sure what you're asking. Setting the library directory to a location on internal storage should allow you to include external media (although this feature is somewhat half-baked). 

If you're experiencing crashes, please create a new issue after capturing the relevant logs using logcat or an app like [this one](https://play.google.com/store/apps/details?id=com.conena.logcat.reader&hl=en_US).

**Comment by Raghucharan16** [comment]
I'm not sure how to put the requirement here, for me app should ask permission to read all storage files and then able to play on device media [songs]. even in the 0.4 release i guess it is not there.
