### ISSUE TITLE
Load more on playlists with 200+ songs will only load the last few songs 

### ISSUE THREAD

**Issue by pikuse** [toasterofbread/spmp#334]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Add a song to a playlist that has (e.g. 250) songs
2. Click load more (down arrow button)
3. Only the last page (last 50) is loaded

### Expected behavior

It should load the next 100 songs, not the last few

### Actual behavior

For example, the load more button then only loads the last 50 songs of a 250 song playlist, not the next 100

### Screenshots / recordings

https://github.com/toasterofbread/spmp/assets/109040953/cf62cfdd-356b-4df5-acc7-c37e8d4f5552

### Logs

None

### SpMp version

0.4.0-beta1 731c72a

### SpMp platform

Android

### OS version

Android 14

### Additional information

Doesn't happen if the playlist is loaded for the first time (or after a data clear), and I also haven't tested this on playlists by other users

**Comment by pikuse** [comment]
Title is a bit misleading, this happens on all playlists

**Comment by toasterofbread** [comment]
I'm not entirely sure what the issue is, and I wasn't able to reproduce it. 3a075cd might help?

> Add a song to a playlist
I tried adding a song to a playlist, then loading the continuation, but this seems to work fine. It didn't look like you added a song in the recording though, could you clarify what you meant by this?

**Comment by pikuse** [comment]
3a075cd seems to have fixed the issue. Here is what I did:https://github.com/toasterofbread/spmp/assets/109040953/821c0494-c515-4571-bbfc-68e28090eba3

The video is from one of the previous commits. The playlist here is supposed to have 311 songs, but instead it loaded 111 (missing another 200)
