### ISSUE TITLE
[Feature Request] Edit to the download system

### ISSUE THREAD

**Issue by v0llk** [toasterofbread/spmp#335]
Would it possible for the download system to also download the song's metadata, such as the song's name, the artist, the album, and the song's thumbnail?
I'm asking because the code to download songs is already implemented, I assume also making it include metadata shouldn't be hard but will greatly improve user experience for people such as myself who use an offline music player.

Thank you for your time.

**Comment by Raghucharan16** [comment]
@v0llk Which offline player do you use, I raised an issue to just allow to read devices files so this player itself acts as offline player.

**Comment by toasterofbread** [comment]
The song name, artist, album, artist URL, and lyrics URL are already written to downloaded song files. I'm not planning on adding thumbnail embedding for performance reasons (as SpMp is primarily a music player, not a downloader).

**Comment by mags-issues** [comment]
If this is already implemented, then there is some bug, because I don't get any metadata other than song name. All of these songs had artist metadata present in spmp:
![Screenshot_20240915-225032_Gramophone](https://github.com/user-attachments/assets/42df3af8-77f4-4fed-bd0e-d478855a9110)
