### ISSUE TITLE
Lyrics not showing/not english

### ISSUE THREAD

**Issue by rairay91** [toasterofbread/spmp#336]
Lyrics for most songs are not showing. Also sometime for some songs lyrics language is not english but they are in japanese or other language.
Also i have a feature request, please add an option which we once enabled lyrics should automatically start showing over music thumbnail. Right now we have to do it manually.

https://github.com/toasterofbread/spmp/assets/77096676/b3a7d90c-8aa6-49ae-be35-2ebf5d22813f

**Comment by toasterofbread** [comment]
> Lyrics for most songs are not showing. Also sometime for some songs lyrics language is not english but they are in japanese or other language.

SpMp uses third-party providers for song lyrics

> Also i have a feature request, please add an option which we once enabled lyrics should automatically start showing over music thumbnail. Right now we have to do it manually.

Lyrics can be opened with a long-press on the song image. This can be configured to be a short-press. Is this better?

**Comment by rairay91** [comment]
> > Lyrics for most songs are not showing. Also sometime for some songs lyrics language is not english but they are in japanese or other language.
> 
> SpMp uses third-party providers for song lyrics.
> 
> > Also i have a feature request, please add an option which we once enabled lyrics should automatically start showing over music thumbnail. Right now we have to do it manually.
> 
> Lyrics can be opened with a long-press on the song image. This can be configured to be a short-press. Is this better?

🤔But other foss youtube player using same third-parties lyrics provider, and lyrics shows for all songs and also in english. I have tried "SimpMusic, InnerTune", both shows lyrics and using same prociders.

**Comment by toasterofbread** [comment]
Could you give a few examples of song IDs that have correct lyrics in InnerTune but not in SpMp?

**Comment by spl3g** [comment]
I think both InnerTune and SimpMusic are using Musixmatch for their lyrics, so there will be a lot more songs with lyrics.

**Comment by toasterofbread** [comment]
It looks like SimpMusic might (not sure), but InnerTune doesn't use MusixMatch for the [same reason](https://github.com/z-huang/InnerTune/issues/1440#issuecomment-2305995293) that SpMp doesn't use it.

**Comment by spl3g** [comment]
Oh yeah, sorry. They use lrclib.

**Comment by fuzi0nz** [comment]
@rairay91 did you find a solution yet? Mine won't show lyrics in English either even when changing the default language in the app.

**Comment by Rafee-M** [comment]
@toasterofbread Thoughts on adding lrclib?
