### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by sucooer** [toasterofbread/spmp#340]
The login instructions for the Chinese interface are incorrect, and attempting to log in using the request header results in an error.![Screenshot_20240709_221121.jpg](https://github.com/toasterofbread/spmp/assets/59865283/9affc19b-a1ad-4251-8dc8-cf12262271af)

![IMG_20240709_221339.jpg](https://github.com/toasterofbread/spmp/assets/59865283/9f66926c-ecae-42ab-9c35-b7149e6b0b3b)

**Comment by toasterofbread** [comment]
Please provide the information specified in the [bug report template](https://github.com/toasterofbread/spmp/issues/new?assignees=&labels=Bug&projects=&template=bug_report.yml).

**Comment by sucooer** [comment]
I successfully logged in with version [0.4.0 beta1](https://github.com/toasterofbread/spmp/actions/runs/9964975007).😊
