### ISSUE TITLE
Flatpak: runtime org.freedesktop.Platform/x86_64/23.08 was not found

### ISSUE THREAD

**Issue by yuki-was-taken** [toasterofbread/spmp#341]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Add the spmp flathub repo
2. Try to install spmp and spmp-server
(basically I followed the instructions at https://spmp.toastbits.dev/docs/0.4.x/client/installation-flatpak/)

### Expected behavior

spmp would install

### Actual behavior

Instead of installing it, it gives me this error:
`error: The application dev.toastbits.spmp-server/x86_64/master requires the runtime org.freedesktop.Platform/x86_64/23.08 which was not found`

### Screenshots / recordings

![20240710_23h04m18s_grim](https://github.com/toasterofbread/spmp/assets/141553384/e4328578-a468-49ff-978e-389ac0b28bf8)

### Logs

```
Looking for matches…
error: The application dev.toastbits.spmp-server/x86_64/master requires the runtime org.freedesktop.Platform/x86_64/23.08 which was not found
```

### SpMp version

0.3.2

### SpMp platform

Linux

### OS version

Alpine Linux Edge

**Comment by toasterofbread** [comment]
Does it work if you add the Flathub repo?
`flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

**Comment by yuki-was-taken** [comment]
Yes, it works! Thank you!
