### ISSUE TITLE
[FEATURE REQUEST FOR ANDROID] Display the full song title in the player.

### ISSUE THREAD

**Issue by Avichal1234** [toasterofbread/spmp#342]
When I play a pre-made playlist or basically any song with a very long name, it's full name doesn't appear in the player. The part which doesn't fit gets cut-off.
Could it be made possible for a similar thing like Spotify or YouTube music to be created? Like the title displays and if some words overflow then it scrolls the full title horizontally.

**Comment by toasterofbread** [comment]
Most cut-off text like this in SpMp (including the player title) can be scrolled manually.
