### ISSUE TITLE
Current theme changes with delay

### ISSUE THREAD

**Issue by artiekra** [toasterofbread/spmp#347]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Go into the settings menu
2. Open the "Theming" section of the settings ("Current theme" is whats gonna be changing)
3. The default is "System theme" (1/14); switching from it to "Catppuccin Mocha (mauve)" (2/14) and vice-versa seems fine, but a bit laggy.
4. Switch from "Catppuccin Mocha (mauve)" (2/14) to any other theme from the next ones.

### Expected behavior

The theme should immidiately switch to the selected one; the number (n/14) should be updated, as well as the theme name in the selection menu.

### Actual behavior

Nothing happens after button presses. To apply the theme correctly, you have to exit the theming section, and enter it again.

### Screenshots / recordings

https://github.com/user-attachments/assets/52daf26e-7105-4230-89cb-4f525a681db3

### Logs

None

### SpMp version

SpMp non-release build on 33d7f79 and API version 2 (spmp-0.4.0-beta1.apk-debug.apk)

### SpMp platform

Android

### OS version

Android 9; EMUI 9.1.0

### Additional information

Doesn't happen on release build v0.3.2

**Comment by toasterofbread** [comment]
This will be fixed when #345 is merged

**Comment by toasterofbread** [comment]
I was never able to reproduce this, but it should be fixed now. Feel free to comment if not.
