### ISSUE TITLE
`Reading metadata failed` issue

### ISSUE THREAD

**Issue by artiekra** [toasterofbread/spmp#348]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce

The cause may be some errors when downlodading.. The issue might be related to #244, but for me appears, when i open the app, thats.. how i reproduce it?

### Expected behavior

The app should open and function normally.

### Actual behavior

Getting the mentioned error. When i go back on my phone, the error persists, i can't enter SpMp, even after a full app restart.

### Logs

https://paste.ee/p/S3ZmK

### SpMp version

SpMp non-release build on 33d7f79 and API version 2 (spmp-0.4.0-beta1.apk-debug.apk)

### SpMp platform

Android

### OS version

Android 9; EMUI 9.1.0

### Additional information

In my downloaded music folder (which is custom), for some reason, i had two of.. the same songs saved. Deleting one of them resolved the issue, maybe this can be prevented from happening?

**Comment by toasterofbread** [comment]
I had another look at #244 when you posted this, and the issue turned out to be fairly obvious (not sure how I missed it before) so that one's fixed now. This one might also be fixed, not sure.
