### ISSUE TITLE
Add song to existing YT playlist

### ISSUE THREAD

**Issue by Geigerkind** [toasterofbread/spmp#351]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Clean fresh install of the app
2. Log in to YT
3. Try to add a song to a playlist

### Expected behavior

My YT playlists should be displayed there

### Actual behavior

Nothing is displayed.

### Logs

Did not encounter an error.

### SpMp version

0.4.0-RC-1

### SpMp platform

Android

### OS version

Android 12

**Comment by toasterofbread** [comment]
Are playlists the only thing that aren't synced with your account? What about the home feed, radios, albums, etc.?

Additionally, does this occur on the latest stable version (v0.3.2)?

**Comment by Geigerkind** [comment]
Hey. 
I have not tried 0.3.2 because I couldnt log into my account there.
On 0.4.0-RC-1 I could but couldnt choose my account.

Home feed works. 
Playlists dont show up in the Playlists tab, if thats intended behavior.
Radio works.

I tried to add the song while being on a song, tapping on the 3 dots, clicking add playlist and in this tiny sub menu no playlists show up. 

Just tried it again and now im also getting an error message:
Going to figure out how to get the logs.

**Comment by Geigerkind** [comment]
Seems to work in 4.0 again!
