### ISSUE TITLE
YT playlist initial fetch only loads 100 songs

### ISSUE THREAD

**Issue by Geigerkind** [toasterofbread/spmp#352]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Log in to YT
2. Open a Playlist you havent fetched yet
3. Playlist should have more than 100 songs

### Expected behavior

All songs are fetched

### Actual behavior

Only 100 songs are fetched and I have to scroll down to load more.

### Logs

There were no errors.

### SpMp version

0.4.0-RC-1

### SpMp platform

Android

### OS version

Android 12

**Comment by toasterofbread** [comment]
This is intended behaviour
