### ISSUE TITLE
With broken songs, weirdness begins

### ISSUE THREAD

**Issue by Vladik01-11** [toasterofbread/spmp#356]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Play the song several times so that it downloads and saves locally
2. At the time when it should load, turn off the Internet, the application will stop or something like that.
3. If it stops playing during playback, then a bug has been fixed.

### Expected behavior

Correct song playback

### Actual behavior

It can be both together and separately:
Extraneous noise;
Low volume;
Any songs stop playing until the app stops completely.

### Screenshots / recordings

At the end of the first session, the defective song began to play with interference + blocking the playback of songs, and in the second only blocking.

https://github.com/user-attachments/assets/c34e0bf5-8bd5-49cb-9616-6e1a49db2f4b

### Logs

[12_08-18-31-12_220.zip](https://github.com/user-attachments/files/16588998/12_08-18-31-12_220.zip)

### SpMp version

0.4.0 Beta (e6ed0ea)

### SpMp platform

Android

### OS version

Android 13, NoRoot

### Additional information

This error is very rare, which makes it difficult for me to catch logs, and so once because of this, logs for the release version were provided.
Because I can easily catch the current bug on the release version, because now there is a song on it, because of which it is being played. This does not mean that the bug is not in the debug version, it is just unknown when it will occur in the debug version.
Both songs have already been saved on the device where the first beat is (or something is wrong with it)

**Comment by toasterofbread** [comment]
Try [this build](https://github.com/toasterofbread/spmp/actions/runs/10355930913)

**Comment by toasterofbread** [comment]
I only see the first song (B66nlOL7LCY) being played in that log. Are you sure you performed the same actions (playback of both songs breaking)?

**Comment by toasterofbread** [comment]
Hmm, neither of those logs seem to contain any useful indicators.

A few questions:
- You said the issue is rare. Is it rare to find a song that triggers the issue, or does it occur rarely even for a specific song? Does it seem to happen with every song?
- When you say 'At the time when it should load', what do you mean exactly?
