### ISSUE TITLE
Can't access main page

### ISSUE THREAD

**Issue by abdallahmehiz** [toasterofbread/spmp#360]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open the app

### Expected behavior

App should open on feed and i should be able to explore it

### Actual behavior

An exception gets thrown

### Screenshots / recordings

![Screenshot_20240823-180428](https://github.com/user-attachments/assets/3dfff26a-3fef-43a5-b757-503860d4a5ad)

### Logs

https://paste.ee/p/FkpOx

### SpMp version

0.4.0

### SpMp platform

Android

### OS version

Android 14 QPR2

### Additional information

I've also tried it on my friend's phone with android 12 but same issue.

**Comment by ZTRdiamond** [comment]
me too, the app is broken :(

**Comment by blissashly29** [comment]
Please, solve the problem. 😞

**Comment by toasterofbread** [comment]
Fixed in [v0.4.1](https://github.com/toasterofbread/spmp/releases/tag/v0.4.1)
