### ISSUE TITLE
Minor UI bug: Every time a new song plays with video on background, video is not centered.

### ISSUE THREAD

**Issue by C-H-Rm** [toasterofbread/spmp#362]
This always occurs when video position is set to player background and are currently in the player while the song changes and the video loads in.

![Screenshot_20240825-135117.png](https://github.com/user-attachments/assets/3f69af9d-2712-4299-95e9-d96c2037fa62)

The video does get correctly centered when you either go to queue or swipe down the player.

I run grapheneOS on a google pixel 7
And use spmp version 0.4.1

**Comment by toasterofbread** [comment]
(Please use the issue template when reporting bugs)

I'm unable to reproduce this. What's your Android version?

**Comment by C-H-Rm** [comment]
> (Please use the issue template when reporting bugs)
> 
> I'm unable to reproduce this. What's your Android version?

GrapheneOS with Android 14

I also tested this on a samsung s10 lite running oneUI and didnt get this issue. Its likely related to grapheneOS if i had to guess.

**Comment by toasterofbread** [comment]
I've been unable to reproduce this on any device or Android version. Are you sure there aren't more factors involved with this issue (other theming settings, type of video, etc.)?

**Comment by C-H-Rm** [comment]
> I've been unable to reproduce this on any device or Android version. Are you sure there aren't more factors involved with this issue (other theming settings, type of video, etc.)?

Commit 2cb2125ec4146a275872668e22f7627c8f3d1108
Fixed the issue
