### ISSUE TITLE
[Feature request] Cast to DLNA/UPnP receivers

### ISSUE THREAD

**Issue by deaksa** [toasterofbread/spmp#381]
Hi

Would it be possible to add a feature to cast to dlna/upnp enabled audio devices? Native youtube apps supports only cromecast which is only supported by a few devices, while dlna/upnp is widely supported. 

There are tons of foss (local)music player apps with this feature, but non with youtube music support.

**Comment by toasterofbread** [comment]
Sorry, not planned.
