### ISSUE TITLE
New song or resume randomly hangs

### ISSUE THREAD

**Issue by lake-effect** [toasterofbread/spmp#383]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Start or resume app as anonymous user
2. Resume a song from standby or search a new song
3. Wait for playback
4. Observe playback may never start, or take as much as 20 minutes with no feedback

### Expected behavior

1. Playback should happen promptly with a good internet connection, or a meaningful error should appear

### Actual behavior

1. App just sits with play button displayed and throbber or spinner cycling 

### Screenshots / recordings

![Screenshot_20241010-104345](https://github.com/user-attachments/assets/11243d57-762a-453a-94e7-ece3375b7402)
![Screenshot_20241010-104358](https://github.com/user-attachments/assets/696a5048-053c-41af-ad58-4977f9855694)

### Logs

[SpMp (debug) log c7f28633aae0.txt](https://github.com/user-attachments/files/17332096/SpMp.debug.log.c7f28633aae0.txt)

### SpMp version

Nightly debug 2024/10/10

### SpMp platform

Android

### OS version

Android 14 (GrapheneOS)

### Additional information

This bug occurs maybe 40%-60% of the time.

**Comment by toasterofbread** [comment]
Does this occur when using the NewPipe streaming method on the [latest build](https://github.com/toasterofbread/spmp/actions/runs/11505238115)? Set it in the playback section of settings and also disable the "Fall back to other stream methods" option.

**Comment by lake-effect** [comment]
It looks like NewPipe fixes it! There's a bug there where song metadata no longer shows on Bluetooth devices, but I'll test that with debug build and file separately

**Comment by toasterofbread** [comment]
@lake-effect See #393

**Comment by lake-effect** [comment]
Thanks!
