### ISSUE TITLE
Failing maxresdefault images not falling back to low quality images

### ISSUE THREAD

**Issue by pikuse** [toasterofbread/spmp#390]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open a song (specifically, user-uploaded ones that aren't 720p or above)
2. There it is

### Expected behavior

Player image loads and doesn't display a grey youtube icon.

### Actual behavior

Player image displays a grey youtube icon.

### Screenshots / recordings

![Screenshot_2024-10-24-01-52-19-59_e82a23cb50dd4a2f2e01332c4ab3b632](https://github.com/user-attachments/assets/b594b908-d481-49e2-8351-eb0616cd59da)

### Logs

https://paste.ee/p/eIVk9

### SpMp version

0.4.1 880fabf

### SpMp platform

Android

### OS version

Oxygen OS 14.0.0.550

### Additional information

I can't pinpoint exactly at what commit this bug started occurring.

**Comment by toasterofbread** [comment]
This was something I noticed recently on many songs (not just user-uploaded), looks like YouTube recently changed the way maxresdefault images are provided. Should work now.
