### ISSUE TITLE
Pressing back once on the player doesn't repeat the song

### ISSUE THREAD

**Issue by gram11111111** [toasterofbread/spmp#398]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Pressing the back button once

### Expected behavior

When the back button is pressed once it repeats the current song

### Actual behavior

The back button just goes back to the previous song, or if there is no previous song it does nothing

### Logs

non

### SpMp version

0.4.2

### SpMp platform

Android

### OS version

android 12

### Additional information

The song repeats if the back button is pressed in the notification 
Song doesn't repeat with headphone controls

**Comment by toasterofbread** [comment]
Not repeating the song is intended behaviour. I've fixed the notification button to match the player button (I think this was a recent regression).

**Comment by gram11111111** [comment]
ah ok, is it possible for this to be a feature? Maybe something that can turned off or on, because I am just so used to being able to repeat the song with my headphones by just going back in other players.

**Comment by toasterofbread** [comment]
@gram11111111 That's possible, yeah. Please make an issue for the feature request.
