### ISSUE TITLE
No Scroll Bar

### ISSUE THREAD

**Issue by Skylarisdeadcri** [toasterofbread/spmp#406]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

My scroll wheel does not work on my mouse. Please add the scroll bar back

### Expected behavior

Application Should have a scroll bar

### Actual behavior

No Scroll wheel.

### Logs

None

### SpMp version

0.4.2

### SpMp platform

Windows

### OS version

Windows 11 Home 23H2

**Comment by toasterofbread** [comment]
Please provide more detail. Which screen(s) are missing scrollbars?
