### ISSUE TITLE
Songs not playing when logged in

### ISSUE THREAD

**Issue by SafeNut** [toasterofbread/spmp#417]
### Checklist

- [ ] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Log into youtube
go to any song
press play
doesnt play

### Expected behavior

Song should play with audio

### Actual behavior

song does not play, if in a playlist it will continually go to the next track

### Logs

Unable to find logs

### SpMp version

0.4.1

### SpMp platform

Linux

### OS version

Bazzite 41

### Additional information

works fine when not logged in
unable to test on latest debug build, likely user error but i cant get it to run
had to use manual login as the sign in page is broken (cURL of POST https://music.youtube.com/youtubei/v1/browse?prettyPrint=false)

**Comment by BludAdit3220** [comment]
same problem it just started recently

**Comment by toasterofbread** [comment]
Please don't create issues based on old versions. This is a known issue and has been (at least partially) fixed in v0.4.2 and more recent commits. If you're having a problem using the latest build, create an issue for that instead.

**Comment by BludAdit3220** [comment]
thanks
