### ISSUE TITLE
Logging into Discord through app leads to a crash

### ISSUE THREAD

**Issue by TicTecOfficial** [toasterofbread/spmp#60]
Am using the latest spmp version, tried logging into Discord through that but no luck as it crashes the app moments after logging in

**Comment by toasterofbread** [comment]
Should be fixed! Thanks for the report.
I'll make a release later, but you can test it in the meantime once the [GitHub action](https://github.com/toasterofbread/spmp/actions/runs/5526443254) finishes building (although that might have its own bugs).
