### ISSUE TITLE
APK at tag v0.1.1 identifies as 0.1.0

### ISSUE THREAD

**Issue by IzzySoft** [toasterofbread/spmp#62]
Just wanting to check if there's the correct APK attached, as it identifies as

    package: name='com.toasterofbread.spmp' versionCode='2' versionName='0.1.0'

while the tag name suggests a `versionName` of `0.1.1`, and the number of releases a `versionCode` of `> 3` (it's the 4th release). Could you please replace it by the correct one? Thanks in advance!

**Comment by toasterofbread** [comment]
I've replaced the v0.1.1 APK with one with the correct version.

**Comment by IzzySoft** [comment]
Thanks a lot! Then let's raise visibility a bit: with the next sync around 6 pm UTC (i.e. in about 19h from now) your app will become [available here](https://apt.izzysoft.de/packages/com.toasterofbread.spmp/) in my repo. New versions will become available within 24h from your creating a new release and attaching the APK to it (with the proper versioning :wink:). If you like what you see then, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

**Comment by toasterofbread** [comment]
Awesome, thanks! I'm planning on adding the app to the main F-Droid repo once I've smoothed out the app a fair bit more, but that probably won't be for a few months at least.

**Comment by IzzySoft** [comment]
See you over there then when the time comes (disclosure: I'm one of the F-Droid maintainers) :smiley:
