### ISSUE TITLE
[SUGGESTION] add/use kugou.com as alternative lyric source 

### ISSUE THREAD

**Issue by TicTecOfficial** [toasterofbread/spmp#63]
kugou.com has similar(i think) features as PetitLyrics as imo it has a wider source of lyrics than Petit and also has support for timed/synchronized lyrics.

Also, i think it's worth noting that this website/source is what ViMusic uses as well.

**Comment by toasterofbread** [comment]
Thanks for the suggestion. I'm busy with some major fixes and improvements at the moment, but I'll definitely implement this once I find the time, and make it easier for further lyrics sources to be added.
