### ISSUE TITLE
Bug: clicking on podcast throws error

### ISSUE THREAD

**Issue by emkay5771** [toasterofbread/spmp#65]
https://paste.ee/p/zdz25

**Comment by toasterofbread** [comment]
Could you give an example of a podcast URL please?

**Comment by Chibitech** [comment]
I'm not 100% certain if this is related, but I noticed that just now installing the app and opening it immediately gives this:
https://paste.ee/p/TSiqM
The app goes unresponsive afterwords and has to be closed

**Comment by toasterofbread** [comment]
> I'm not 100% certain if this is related, but I noticed that just now installing the app and opening it immediately gives this

Are you using the [latest build](https://github.com/toasterofbread/spmp/actions/runs/5556932257)? This crash should be fixed in that.

**Comment by Chibitech** [comment]
Ah, no it seems not. I just found the app on F-Droid a few minutes ago.
The latest build works, thank you

**Comment by emkay5771** [comment]
> Could you give an example of a podcast URL please?

https://music.youtube.com/playlist?list=PL70yIS6vx_Y2xaKD3w2qb6Eu06jNBdNJb&feature=share

**Comment by toasterofbread** [comment]
I've fixed all the crashes major issues I found. Podcast playback should work roughly the same as playing regular songs for now. 

I'll implement UI for podcasts (#68) some point, but it probably won't be a priority for a while.
