### ISSUE TITLE
Monochrome themed icon (Android 13+)

### ISSUE THREAD

**Issue by danielphan2003** [toasterofbread/spmp#74]
For Material You theming on home screen.

**Comment by toasterofbread** [comment]
I'm not familiar with how this would be implemented. Could you link to some documentation?

**Comment by danielphan2003** [comment]
Here: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by toasterofbread** [comment]
> Here: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

Thanks, will look into soon

**Comment by toasterofbread** [comment]
[Added!](https://github.com/toasterofbread/spmp/commit/8e2165b3ed04388d2b7f6d86c5d42669d9a60a20)

**Comment by sebastien46** [comment]
Not working properly on GrapheneOS (default camera app for reference):
![IMG_20230723_210303 1](https://github.com/toasterofbread/spmp/assets/57289288/07a59338-6660-4c07-bcc5-8d4113507e43)
