### ISSUE TITLE
[FEATURE] Exclude songs with title containing keywords

### ISSUE THREAD

**Issue by ComplicatedT** [toasterofbread/spmp#77]
Currently, as far as I am aware, no music streaming service or custom client offers a feature that allows the blocking(not playing) of songs that contain specific keywords in song's lyrics or title. This is quite frustrating to me since music recommendations would be so much better if I were able to block specific keywords. I know that this is a niche feature but I lack skills to develop such functionality myself. Thank you for your time.

**Comment by toasterofbread** [comment]
Sure, that sounds like a great feature. Would an editable list of blocked keywords in the settings work fine?

**Comment by ComplicatedT** [comment]
Yes, it would be awesome.

**Comment by toasterofbread** [comment]
Implemented!

I've added a 'Filter' section to the settings with an editable list of keywords that are matched against song/artist/playlist titles.
The filter is applied to the home feed and song queue by default, and can be enabled additionally for the playlist page and artist page.
