### ISSUE TITLE
[Feature] Setting for queue item dismiss sensitivity

### ISSUE THREAD

**Issue by MrConqueror** [toasterofbread/spmp#78]
this area is very sensitive like i was scrolling then some songs starts to gone missing, you slightly swipe left or right then it's gone. i hope you can do something about it.

![Screenshot_2023-07-19-14-30-04-697_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/102837820/6b2b0341-4447-4110-a8fb-f27b7a7e5cf2)

**Comment by toasterofbread** [comment]
I'll look into this

**Comment by toasterofbread** [comment]
This has been added as a slider to the player category. The default sensitivity has also been lowered, so you might not need to change the setting.
