### ISSUE TITLE
[Feature] Material You

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [toasterofbread/spmp#80]
Is it possible to make an option for the player follow the devices dynamic colouring? It would make this app perfect!

**Comment by toasterofbread** [comment]
I thought I'd already implemented this (although only for the accent colour) but it doesn't seem to be working, I'll work on a fix.

**Comment by TeaEndsAcronyms** [comment]
Yeah, I was 90% sure it was this. But it didn't seem to be working. Thanks!
[Screenshot_20230719-190355~2.png](https://github.com/toasterofbread/spmp/assets/123305689/443b969d-d390-4ec9-844d-eba44d6796d3)

**Comment by toasterofbread** [comment]
Fixed and added support for the background colour.

**Comment by TeaEndsAcronyms** [comment]
Thanks! :)
