### ISSUE TITLE
[Feature request] Device Broadcast Status

### ISSUE THREAD

**Issue by dishapatel010** [toasterofbread/spmp#85]
Allow other apps on devices to see what your listening, so it would be easy to use scrobbler

**Comment by toasterofbread** [comment]
I'm not sure what you mean by this. Is this a specific API you're talking about? If so, please link to some documentation.

**Comment by dishapatel010** [comment]
> I'm not sure what you mean by this. Is it a specific API you're talking about? If so, please link to some documentation about how it can be implemented.

I mean like [scrobble](https://play.google.com/store/apps/details?id=com.arn.scrobble) takes what we are listening from notification & then does it rest work. So the app should support broadcasting or showing NOTIFICATION what it is playing.

[This might be](https://developer.android.com/reference/android/content/BroadcastReceiver.html) as docs or maybe some other way to show out the notification

**Comment by toasterofbread** [comment]
I'm still not sure what you mean. There's already a notification displaying the currently playing song, but I'm guessing you're not talking about that. The BroadcastReceiver docs you linked don't seem to have anything to do with scrobbling unless there's an API it can be used to communicate with.

Do you mean that SpMp should directly include support for LastFM or other services? (I'm already planning on adding this)
Or do you mean that it should be compatible with apps like the one you listed?

**Comment by dishapatel010** [comment]
> I'm still not sure what you mean. There's already a notification displaying the currently playing song, but I'm guessing you're not talking about that. The BroadcastReceiver docs you linked don't seem to have anything to do with scrobbling unless there's an API it can be used to communicate with.
> 
> Do you mean that SpMp should directly include support for LastFM or other services? (I'm already planning on adding this) Or do you mean that it should be compatible with apps like the one you listed?

I see that there is notification but it's not showing metadata. So if i want that scrobbler to work with this app it should get captured.

**Comment by toasterofbread** [comment]
> I see that there is notification but it's not showing metadata. So if I want that scrobbler to work with this app it should get captured.

So the notification isn't showing the song title and artist? It should look roughly like this. The buttons might not appear on some Android versions that I haven't implemented yet, but the title and artist should at least show up.

If that's the case, what version of Android are you using? And could you send a screenshot of what the notification looks like for you? 

<img src="https://github.com/toasterofbread/spmp/assets/44363049/ad4c7073-becc-4c94-8c3a-2da6090f0001" height=500/>

**Comment by dishapatel010** [comment]
> > I see that there is notification but it's not showing metadata. So if I want that scrobbler to work with this app it should get captured.
> 
> So the notification isn't showing the song title and artist? It should look roughly like this. The buttons might not appear on some Android versions that I haven't implemented yet, but the title and artist should at least show up.
> 
> If that's the case, what version of Android are you using? And could you send a screenshot of what the notification looks like for you?
> 
> <img alt="" height="500/" src="https://user-images.githubusercontent.com/44363049/254901873-ad4c7073-becc-4c94-8c3a-2da6090f0001.png">

![Screenshot_20230720-202556~2](https://github.com/toasterofbread/spmp/assets/71930916/9dfb77cc-e2a9-4610-aa08-cacfa682ae95)
Title & artist are shown. I'm on Android 11 Moto e40. (It doesn't get through scrobbler & when i remove app from recents & notification it still plays without any notification)

**Comment by toasterofbread** [comment]
> It doesn't get through scrobbler

How can I support that then? I can't add support for something without knowing how the API works. Is this specific to the scrobbler app you mentioned or is it a more general scrobbling system?

**Comment by dishapatel010** [comment]
> > It doesn't get through scrobbler
> 
> How can I support that then? I can't add support for something without knowing how the API works. Is this specific to the scrobbler app you mentioned or is it a more general scrobbling system?

Basically it should throw out metadata i like ideal music player would. Ex- YouTube music app or [Retro music ](https://github.com/RetroMusicPlayer/RetroMusicPlayer).
I should suggest look into this retro music code.

If everything is correct scrobbler would work without any doubt
![Screenshot_20230721-224045~3](https://github.com/toasterofbread/spmp/assets/71930916/32cf5b4f-4d19-42f4-a8a5-e45e7cfd7e16)

**Comment by toasterofbread** [comment]
I'm sorry, but I really don't have the time to sift through another codebase to figure out how they're implementing the metadata bridge. I had a glance at both apps you linked and I didn't see any obvious documentation or code related to media metadata for scrobbling. Googling about Android media metadata didn't reveal anything either.

I don't use a scrobbler myself, so I don't know exactly how they work and can't test with one easily. If you can find specific documentation about how to add the functionality then I might be able to implement it.

Sorry if this comes across as cold, I'd love to implement this but I just have absolutely no idea how to. I do still plan to add built-in scrobbling at some point though.

**Comment by dishapatel010** [comment]
> I'm sorry, but I really don't have the time to sift through another codebase to figure out how they're implementing the metadata bridge. I had a glance at both apps you linked and I didn't see any obvious documentation or code related to media metadata for scrobbling. Googling about Android media metadata didn't reveal anything either.
> 
> I don't use a scrobbler myself, so I don't know exactly how they work and can't test with one easily. If you can find specific documentation about how to add the functionality then I might be able to implement it.
> 
> Sorry if this comes across as cold, I'd love to implement this but I just have absolutely no idea how to. I do still plan to add built-in scrobbling at some point though.

Okay, if i find will mention it. Thanks for your support.
