### ISSUE TITLE
[Feature Request] Android TV Support

### ISSUE THREAD

**Issue by peat80** [toasterofbread/spmp#89]
It would be aesome if this app could get support for android tv / non touch devices in a future version.

Landscape layout looks fine already on tv but navigation with remote does just work partially.

**Comment by toasterofbread** [comment]
Could you explain what already works with the TV navigation? I've looked into how I could support this but there doesn't seem to be any documentation about how to support remote controls (sorry about the late response).

**Comment by peat80** [comment]
The remote control seems to work already.
I can for example focus the settings button and by pressing ok it opens.
I can scroll there through the entrys and change settings but you have to guess or count where you are.
The active row does not get highlighted.
This would be necessary for remote navigation.

On the views which contains actual content i cannot reach an entry. Only scrolling is working.

So actually i cannot play anything. 🤔

**Comment by peat80** [comment]
The filter row and top buttons actually work like they should. Navigating there does highlight the actual entry.

**Comment by peat80** [comment]
https://github.com/toasterofbread/spmp/assets/32403292/9298354c-6d59-4151-9f98-f931b7c219f8

**Comment by peat80** [comment]
Uploading SpMp_20231031_180845_Wiedergeben.mp4…

**Comment by peat80** [comment]
https://github.com/toasterofbread/spmp/assets/32403292/40aef18c-f8ab-4b52-a47f-264b3f323d72

**Comment by toasterofbread** [comment]
I'm re-evaluating some older issues, and I don't think I'll be implementing this anymore. If anyone can find some documentation on how to implement this I might change my mind though.
