### ISSUE TITLE
Song title on Ambient Display. App don't scrobble with PanoScrobble

### ISSUE THREAD

**Issue by PFARN** [toasterofbread/spmp#90]
Can you add the song title to Ambient Display or AoD?
Please.
Also, the app notification isn't detected by Pano Scrobble, I guess by the same reason that the title isn't displayed on Ambient Display.

**Comment by toasterofbread** [comment]
> Can you add the song title to Ambient Display or AoD?

I'm not familiar with how either of those work. Could you please link to some documentation about how the title can be displayed on them?

> Also, the app notification isn't detected by Pano Scrobble,

See #85

**Comment by PFARN** [comment]
> > Can you add the song title to Ambient Display or AoD?
> 
> I'm not familiar with how either of those work. Could you please link to some documentation about how the title can be displayed on them?
> 
> > Also, the app notification isn't detected by Pano Scrobble,
> 
> See #85

Oke, thanks you for reply. I'll browse for documentation.

 Also, don't happen to you that once you pause the music from the notification in QS, the app get closed, and notification disappear?

**Comment by toasterofbread** [comment]
> Also, don't happen to you that once you pause the music from the notification in QS, the app get closed, and notification disappear?

Immediately after you pause it, or a while later? Sometimes it'll disappear while it's paused and I'm doing something else (will definitely fix this eventually) but it never disappears straight away for me.

**Comment by PFARN** [comment]
Yeah, a while after it gets paused. Well, thanks for your project, the terminal stylish font and the app UI/Color are awesome. I have like two days using it.
