### ISSUE TITLE
MediaItem backend rewrite

### ISSUE THREAD

**Issue by toasterofbread** [toasterofbread/spmp#93]
Currently, MediaItems (songs, artists, and playlists) are all tracked in maps for each type, with each item corresponding to a single object instance which is used everywhere. The data for MediaItems is cached to the disk using JSON files (one for each item). This system is messy, very fragmented (and uses JSON), so I'm rewriting the entire system to use a [SQLDelight](https://github.com/cashapp/sqldelight) database.

Some bugs will have to wait until the MediaItem rewrite is complete before being addressed, as they would probably be fixed by the rewrite anyway.

**Comment by Zaxx69** [comment]
Nice, as of now i found many bugs, after you rewrite it, i will check again and thanks for these app

**Comment by toasterofbread** [comment]
![sql](https://github.com/toasterofbread/spmp/assets/44363049/e82540ba-3911-44ec-acfe-e54c17493ffa)
