### ISSUE TITLE
[Bug] app crash

### ISSUE THREAD

**Issue by Zaxx69** [toasterofbread/spmp#97]
![Screenshot_2023-07-25-11-13-58-38_7c6675ada7b05a8d2d5c5ffa2a487337.jpg](https://github.com/toasterofbread/spmp/assets/138523882/9759d1aa-ceec-4cd5-a2e4-03d0c2c6e7e4)

Today the app crashed when i first opened it.
I cleared the cache and opened it again
The moment i clicked on my playlist.
The app crashed again
Now i cleared the cache as well as force stop
But the app crashed again upon touching my playlist
This time i cleared the app data as well as cache, i will report if it's fixed

**Comment by toasterofbread** [comment]
Sorry, it's basically impossible for me to debug this without more information like a crash log (you should be able to get it with [logcat](https://stuff.mit.edu/afs/sipb/project/android/docs/tools/help/logcat.html) if you can reproduce the issue). There's a good chance this'll be fixed when I finish #93 anyway though.

I'll close this for now until there's more info on the bug.
